### ISSUE TITLE
Filtering reads for having ≥2 T>C conversions

### ISSUE THREAD

**Issue by os306** [t-neumann/slamdunk#100]
Hello,

I am trying to perform differential expression analysis using TcReadCounts in DESeq2 in a similar manner to what Muhar et al described in the [Science paper](https://www.ncbi.nlm.nih.gov/pubmed/29622725). I am sorry if this is a very basic/silly question, but I am slightly confused about the part where it says "reads were filtered for having ≥2 T>C conversions". I have five different tcount tables corresponding to 5 different treatment conditions. When I look at the tcReadCount column in each table, I see numerous genes where the tcReadCount is <2. Do I need to remove these rows from each table before combining them into a data frame that I will input into DESeq2? Or is there a better way of doing this? 

Once again, apologies if this is a basic question - complete beginner here!

**Comment by os306** [comment]
Just as a follow up question from this, if I decided to combine all the tcount files into one data frame beforehand, did decide to remove the rows corresponding to genes where the tcReadCount is <2, would I remove the entire row if all of the samples (i.e. columns) show a value of <2, or when only 1 sample falls below this value? For example, if my dataframe looks something like this:

              TREATMENT 1       TREATMENT 2      TREATMENT 3      TREATMENT 4       TREATMENT 5
GENE 1       100                        150                             160                         75                            60
GENE 2       5                             7                                 8                             1                             6
GENE 3       10                          15                                3                              1                            2
GENE 4       0                            0                                 1                               1                            0

Would I exclude the rows for GENE 2 and GENE 3 in addition to GENE 4 (because each row has at least one column where the tcReadCount is <2? Or would I only exclude the row for GENE 4 (because all the columns have tcReadCounts <2? I would be very grateful for any guidance. Thanks again!
 
| Gene name  | Group 1 |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

**Comment by os306** [comment]
Just as a follow up question from this, if I decided to combine all the tcount files into one data frame beforehand, did decide to remove the rows corresponding to genes where the tcReadCount is <2, would I remove the entire row if all of the samples (i.e. columns) show a value of <2, or when only 1 sample falls below this value? For example, if my dataframe looks something like this:


| Gene symbol  | Treatment 1 | Treatment 2 | Treatment 3 | Treatment 4 | Treatment 5 |  
| ------------- | ------------- |
| Gene 1  | 100 | 150 | 160 |  75 |  60
| Gene 2 | 5  | 7 | 8 |  1 |  6
| Gene 3 | 10  | 15 |  3 | 1 | 2
| Gene 4 | 0  | 0 | 1 |  1 | 0

Should I exclude the row corresponding to Gene 2 and Gene 3 (because they contain at least one column where the tcReadCount is <2, or should I only exclude the row for Gene 4 (as all the columns have tcReadCount values of <2. Apologies again if this is a silly question, but I would be very grateful fo any guidance!

**Comment by os306** [comment]
Just as a follow up question from this, if I decided to combine all the tcount files into one data frame beforehand, did decide to remove the rows corresponding to genes where the tcReadCount is <2, would I remove the entire row if all of the samples (i.e. columns) show a value of <2, or when only 1 sample falls below this value? For example, if my dataframe looks something like this:


| Gene symbol  | Treatment 1 | Treatment 2 | Treatment 3 | Treatment 4 | Treatment 5 |  
| ------------- | ------------- | | ------------- | | ------------- | | ------------- |
| Gene 1  | 100 | 150 | 160 |  75 |  60
| Gene 2 | 5  | 7 | 8 |  1 |  6
| Gene 3 | 10  | 15 |  3 | 1 | 2
| Gene 4 | 0  | 0 | 1 |  1 | 0

Should I exclude the row corresponding to Gene 2 and Gene 3 (because they contain at least one column where the tcReadCount is <2, or should I only exclude the row for Gene 4 (as all the columns have tcReadCount values of <2. Apologies again if this is a silly question, but I would be very grateful for any guidance!

**Comment by os306** [comment]
Just as a follow up question from this, if I decided to combine all the tcount files into one data frame beforehand, did decide to remove the rows corresponding to genes where the tcReadCount is <2, would I remove the entire row if all of the samples (i.e. columns) show a value of <2, or when only 1 sample falls below this value? For example, if my dataframe looks something like this:

| Gene Symbol | Treatment 1 | Treatment 2 | Treatment 3  | Treatment 4 | Treatment 5 |
| --- | --- | --- | --- | --- |
| Gene 1  | 100 | 150 | 160 |  75 |  60 | 
| Gene 2 | 5  | 7 | 8 |  1 |  6 | 
| Gene 3 | 10  | 15 |  3 | 1 | 2 | 
| Gene 4 | 0  | 0 | 1 |  1 | 0 | 

Should I exclude the row corresponding to Gene 2 and Gene 3 (because they contain at least one column where the tcReadCount is <2, or should I only exclude the row for Gene 4 (as all the columns have tcReadCount values of <2. Apologies again if this is a silly question, but I would be very grateful for any guidance!

**Comment by os306** [comment]
Just to follow on from this, if I decided to combine my tcount files into a single data-frame (with each row corresponding to a gene and each column representing one of 5 different treatment groups) and then decided to exclude rows with <2 T>C conversions, would I exclude rows for which the tcReadCount was <2 for one of the 5 columns, or all of the columns? Apologies again if this is a silly question! My data frame would look something like:

| Gene symbol | Treatment 1 | Treatment 2 | Treatment 3 | Treatment 4 | Treatment 5 |
| :---         |     :---:      |     :---:      |      :---:      |      :---:      |
| Gene 1   | 0     | 0    | 0   | 0    |  0    |
| Gene 2   | 0     | 0    | 0   | 0    |  0    |

**Comment by t-neumann** [comment]
Hi @os306 

sorry if that is not clear from the paper - what is meant here that only reads count as `tcReads` if they have at least 2 `T>C` conversions. So you don't have to filter anything from the final table, but you just have to be sure to have 2 `T>C` conversions as threshold for `tcReads` when running slamdunk. 

```
slamdunk all --help

-c CONVERSIONTHRESHOLD, --conversion-threshold CONVERSIONTHRESHOLD
                        Number of T>C conversions required to count read as T>C read (default: 1)
```

or when running only the count step:

```
slamdunk count --help

-c CONVERSIONTHRESHOLD, --conversion-threshold CONVERSIONTHRESHOLD
                        Number of T>C conversions required to count read as T>C read (default: 1)
```

Then the final table has already the properly restricted counts you need.

**Comment by os306** [comment]
Hi @t-neumann,

Thanks very much for your quick reply, this is exactly the information that I was looking for!

I was wondering if I could also ask for your advice/input on the actual downstream differential expression analysis based on the tcount tables from SLAMdunk, please. The drugs I am using and treatment conditions are similar to the BET inhibitor experiments described in the Muhar et al. Science paper, although in a different cell line.

I imported the combined table containing reads from the TcReadCount columns from each treatment group into DESeq2. I also imported a combined table containing reads from the ReadCount column then assigned the size factor from Total to TcreadCount as mentioned in #70.

When I run DESeq2 on the TcReadCount table I am seeing 103 upregulated genes and 52 downregulated genes (FDR ≤ 0.05; abs [log2FC] ≥ 0.5). This number is quite low compared to what I was expecting compared to what was seen in the Science paper. I also ran DESeq2 using the ReadCount column, but this time I am seeing 1153 upregulated genes and 1177 downregulated genes. My understanding was that the values in the ReadCount column reflect steady state gene expression and therefore I am surprised that I am seeing a higher number of differentially expressed genes compared to when I run DESeq2 using the TcReadCount column. This is the opposite of what is seen in Figure 1C of the Science paper. 

Sorry, I'm not sure if this is the right place to post this question, but I just wanted to make sure I'm not doing anything silly with the output from SLAMdunk. Thanks again!

**Comment by t-neumann** [comment]
How many replicates do you have per condition? And what was the incorporation rate in general in your samples?

**Comment by os306** [comment]
Hi @t-neumann, thanks again for responding here. So I have three replicates per condition - the conversion rates were relatively low across the samples (0.05-0.1%) however there is a clear difference between the noS4U control samples and the S4U-treated samples. My experiment involves treating the cells for 6 hours with the BET inhibitors, and labelling with S4U for 1 hour 

The only reason I can think of why there are 10x more differentially expressed genes when I use DeSeq2 to analyse the ReadCount column column is because the  BET inhibitors were left on for too long and that I am capturing a lot of transcriptional changes that occurred before the S4U was added?

**Comment by t-neumann** [comment]
Hi,

the incorporation rates are indeed very low. Can you calculate the RPMu per gene (so tc-readcounts / sum(non-tcreads) * 10e6) and see how many actually and up above and RPMu >= 2?

But I can tell you already that 6 hours pre-treatement defeats the purpose of SLAM-seq to capture immediate transcriptional changes. I guess 50% of your transcripts have a half-life shorter than 6 hours and will be turned over by then and all secondary effects will have set in, so the change will have already translated into steady-state levels which explains why you see so many changes already on the pure ReadCount levels (resembling a regular RNA-seq experiment).

**Comment by os306** [comment]
Thanks @t-neumann, I think you have hit the nail on the head here and perhaps my pure ReadCount levels are contaminated by secondary effects. We attempted to follow a similar protocol to the one described in this paper (https://science.sciencemag.org/content/368/6489/387) in which cells were perturbed for 6 house with BET inhibitors prior to 1 hour of S4U labeling. Nonetheless, what you describe makes a lot of sense...

Regarding calculating the RPMu per gene - I think I can do this, but could you please clarify how I should calculate "sum(non-tcreads)"? I am not sure where to find this information. I initially thought this would be the sum of the "readcount" column in the tcount table, but I realised that this consists of both non-tc and tc-reads?

Thanks again

**Comment by t-neumann** [comment]
Yes the non-tc read count per gene is just implicitely there - you can get it by subtracting the tc-reads from the readcounts.

**Comment by os306** [comment]
Hi @t-neumann, I followed your instructions and calculated the RPMu per gene using the tcount tables for 1 replicate of the control and 1 replicate of the drug-treated sample - in both cases approximately 50% of my list ended up with an RPMu >=2  Could you please tell me what this means? Thanks again for your help and patience.

**Comment by t-neumann** [comment]
50% of the genes sounds like a lot - how many genes do you have in total?

We usually have like 5-6 thousand genes with the arbitrary RPMu>=2 threshold which we simply use to have some baseline cutoff for sufficiently labelled genes

**Comment by os306** [comment]
The total number of genes is 19,531. FYI, this is based on the output from slamdunk where the T>C conversion threshold was left at the default value (i.e. >=1). I still need to re-run slamdunk after setting the stringency cutoff to >=2.

Just to double check - when you perform differential gene expression analysis do you filter out the genes with an RPMU of <2 from each group (i.e. control, drug treated) before inputting this into DESeq2?

Thanks again for your help and advice.

**Comment by t-neumann** [comment]
Ah ok, no then that number is not telling me much, I'd rather wait for the more stringent results.

I do not filter out any genes before putting them into DESeq2, but I do apply postfilters then on the results.

**Comment by os306** [comment]
Hi @t-neumann,

So SLAMdunk was run again with the stringency cut-off of >=2 T>C conversions. I re-ran DESeq2; however, this time I am seeing only 7 upregulated genes and no downregulated genes that meet the criteria for significance. I calculated the RPMu per gene as you previously asked, and this time I am seeing around 5500 genes with an RPMu>=2 (which sounds similar to what you have observed). I'm a bit concerned about the lack of differentially expressed genes now that the strigency filter has been applied and was wondering if you had any thoughts on this?

Also, could I please ask for clarification regarding something you wrote above: **_"So instead of doing a regular library size normalization as with RPM where your sum of total reads is the normalization factor, you use the sum of non-tc read counts as normalization factor for the tc-read counts"_** Does this mean that I should create a non-TC read column (i.e. readcounts -  tc-reads) and use this for normalization? So far I have been running DESeq2 for both ReadCount and TcReadCount, then assigning the size factor from Total (i.e. T>C reads + non-T>C reads) to TcreadCount by typing:
`sizeFactors(TcReadCount) <- sizeFactors(ReadCount)`

Is this not correct?

Thanks again for your insight and help.

**Comment by t-neumann** [comment]
This sounds indeed very weird - would you be willing to share the count table so I could have a look?

For the normalization factor I was referring to the RPMu calculation - the way you used the total read counts as normalizer in DESeq2 looks fine to me.

**Comment by os306** [comment]
Yes, of course, I have just emailed you the files. Thanks again for your responsiveness and for taking the time to troubleshoot this.
