### ISSUE TITLE
Slamdunk parallel processing

### ISSUE THREAD

**Issue by bernt-matthias** [t-neumann/slamdunk#101]
Quick question: is there a difference wrt the results when running:

1. `slamdunk all ... sample1 sample2 ...` and
2. starting `slamdunk all` separately for each sample?

Was just checking the Galaxy tool sources and thought that option 2 would simplify the tool code quite a bit and would make better use of Galaxy's parallel processing capabilities... but this would only work if the 2 options are equivalent.

**Comment by t-neumann** [comment]
Hi,

there is no difference - as in there is no cross-sample information that would be used in one run vs the other.

We actually also simply run it now only for a single sample to make use of multi-processing workflow managers such as Nextflow.
