### ISSUE TITLE
Multimapping is not default and bed file isn't used

### ISSUE THREAD

**Issue by monikaperez** [t-neumann/slamdunk#105]
Hi, @t-neumann. Thanks for the amazing technology.

We are currently processing some slam-seq data. We are running our fork of Slamdunk, [https://github.com/jkobject/slamdunk](https://github.com/jkobject/slamdunk,) which has been slightly modified to map paired-end data with ngm. Our pipeline consists of trimming fastqs with trimgalore and then running `slamdunk all`.

On our first run, we did not explicitly set multimapping to true. In the docs you recommend using the multimapping parameter (`-m`) which we initially thought was the default. If it’s the recommended parameter, why isn’t the default to run with multimapping?

We also saw that the supplied bed isn’t used to filter reads at all when not multimapping and is only used for counts. Instead, the bed file needs to be supplied via the filterbed (`-fb`) or the bed is used for filtering when `-m` is provided. This leads to misinterpretation of the goal of the parameter and is hard to figure out.

We also saw the docs say that for `-m` to work, `-n` needs to be >1 but multimapping worked for our run when n=1.

We have updated it on our fork and will do a pull request shortly.

Best,
Monika

**Comment by t-neumann** [comment]
Hi @monikaperez 

yes while for shorter reads (RL <= 50bp) we do recommend using the multimapper retainment parameter, lately I'm just seeing SLAMseq data with RL > 100bp where I didnt observe any major global changes with or without multimappers.

I think why intuitively I said n needs to be > 1 is that for choosing an alignment for a multimapper, you would need to have at least 2 alternatives provided to choose from. If the first alignment happens to be the correct one, n=1 might also coincidently work.

**Comment by bio-reflector** [comment]
@monikaperez  Seems like a while back but was wdonering, do you just run slamdunk all as normal or use any other parameters?
