### ISSUE TITLE
Multimapping influences output at read length of 152bp

### ISSUE THREAD

**Issue by monikaperez** [t-neumann/slamdunk#106]
Hi, this is another issue which relates to the previous one, [#105](https://github.com/t-neumann/slamdunk/issues/105).

Our `slamdunk all` call is as follows:
`slamdunk all -o res -r Homo_sapiens_assembly38_ERCC92.fasta -b GSE100708_hg38_refseq_062016_ensemblv84_3UTR.bed -t 14 -c 2 -rl 152 -5 12 -N sample1 sample1_val_1.fq.gz sample1_val_2.fq.gz`

We were initially not able to run the tool simply and we had to set `-rl=152` for slamdunk to work. This is because during the count step the extimateMaxReadLength function is returning a maxLength < 0 and the process is terminated.

Moreover, we used the GRCh38 reference file which contains many alt contigs, including for many well known genes like TNF and and many of the HLA genes (e.g. HLA-B, HLA-DRA, HLA-E).

The issue can be seen here: tracks on IGV show multimapping regions with high signal are being completely filtered out because they contain alt contigs. Here is TNF as an example.

![MYB_dTAG_filt_vs_mm](https://user-images.githubusercontent.com/29385314/146209861-5ea809fe-d161-4900-947a-9ab9b23030d5.png)

We reran with the `-m -n 1` parameters added.

The third track is the filtered output of that run which recovered reads in the 3’UTR region. The Matsushima paper and your response in this issue #102 says that the multimapping retainment strategy isn’t needed at max read length of 152. Our data shows that for hg38 alignment, multimapping retainment strategy is necessary to get reads for genes with alt contigs.

Best,
Monika

**Comment by t-neumann** [comment]
Continuing here @monikaperez 

I have to admit we have in our datasets just looked at canonical chromosome sets and therefore were blind to any genes annotated on alt contigs. So in your case indeed it makes sense to also turn multimapper retainment on for longer read lengths.
