### ISSUE TITLE
Signal at alternate contigs lost

### ISSUE THREAD

**Issue by monikaperez** [t-neumann/slamdunk#107]
Hi, @t-neumann. this is another issue which relates to the previous one, [#106](https://github.com/t-neumann/slamdunk/issues/106).

We have run slamdunk 3 different ways. Without multimapping, with multimapping (`-n 1 -m`), and multimapping with alt loci removed:
`slamdunk all -o res -r Homo_sapiens_assembly38_ERCC92.fasta -b GSE100708_hg38_refseq_062016_ensemblv84_3UTR.bed -t 14 -c 2 -rl 152 -5 12 -N sample1 sample1_val_1.fq.gz sample1_val_2.fq.gz`

We used the GRCh38 reference which contains many alt contigs, including for many well known genes like TNF and and many of the HLA genes (e.g. HLA-B, HLA-DRA, HLA-E). We found that regions with alt contigs are filtered out. With multimapping, only reads in the 3’UTR region are recovered.

Based on the docs and Matsushima 2019, the multimapping reassignment strategy is working as expected by discarding non-UTR alignments. This raises the issue that all reads in regions with multimapping reads are being discarded unless they are aligned to annotated 3’UTR regions. This causes common genes to get artificially low read count / tc count.

By removing all alternate loci from the hg38 reference genome we fully recovered the signal at the regions with alternate loci. The tracks with all runs at TNF are shown below. The top 3 tracks were run with the GRCh38 with alternate loci and the bottom 2 tracks were run with the alternate loci removed. The tracks are all on the same scale.

![MYB_dTAG_alt_comp](https://user-images.githubusercontent.com/29385314/146211695-c1e41b36-6f7c-41f2-a148-2de466904484.png)

The 1st and 4th track are the prefiltered bam file just after ngm mapping. 
We see in the 5th track which was run without alternate loci and with `-m -n 1` that the signal isn’t filtered out like it was before. The mapped signal is much higher than before but this doesn't seem to impact the filtered reads at regions without alt configs. See MYC below.

![MYB_dTAG_atl_comp_MYC](https://user-images.githubusercontent.com/29385314/146213316-6e256645-c55c-4955-aef1-37110a703e10.png)

Are there parameters you recommend to include regions with alt loci without losing signal in non-3’UTR regions? Why do we filter out non UTR alignments?

Best,
Monika

**Comment by t-neumann** [comment]
Hm so what I could imagine is that the region in the ALT contig is sufficiently different (1-2 bp difference) to the canonical chromosome that you can unambiguously map reads there. Now if you remove the ALT contig, those reads would simply map to the canoncial region with this additional 1-2 differences which artificially boosts the signal. Does this make sense?

The original rationale why we filter out non UTR alignments is that we cannot decide for multimapping reads where they originate from. Now if they map to an annotated UTR and somewhere intergenic, it's very likely that the intergenic mapping is an artifact and the UTR mapping is the true one. If there's two alignments to two different UTRs, we have no such indications and cannot decide where to place the read, ergo we removed it.
