### ISSUE TITLE
SNP calling based on all samples vs no4SU samples

### ISSUE THREAD

**Issue by crueckle** [t-neumann/slamdunk#108]
Dear Tobias,

we ran into the question why SNP calling is running on all samples and not only on the samples were no 4SU labelling was performed. Is there any specific reason? We see that even with higher cutoffs (-f/-mv 0.8) for the Minimum variant fraction to call a variant the T>C SNPs rise in the 4SU samples compared to unlabelled samples. 

Thank you in advance!

**Comment by t-neumann** [comment]
Hi,

this is just a very crude within sample noise-filter. What we usually do is call variants on a control sample (e.g. the no 4SU labelled) and then supply that VCF file for the entire Slamdunk run with the --vcf parameter.

**Comment by crueckle** [comment]
Great thank you! Which --vcf parameter do you mean? Is it possible to set this file for slamdunk all? In the slamdunk count I only see the -s for The output directory of the snp dunk containing the called variants.

**Comment by crueckle** [comment]
Also, do you just merge the VCF file for different replicates and use it as one annotation?

**Comment by t-neumann** [comment]
There is one (probably not officially documented yet but it shows up in the help):

```
 -v VCFFILE, --vcf VCFFILE
                        Skip SNP step and provide custom variant file.
```

I would merge all replicates for the variant calling and then supply a single vcf file for all samples.

**Comment by crueckle** [comment]
Thank you, great! One final question; would you go-to Minimum variant fraction then be 0.2?

**Comment by t-neumann** [comment]
If have diploid cells, then this is what we used in the past.

**Comment by Choopanian-Peyman** [comment]
Hi,
I run slamdunk on your test data with following command, but vcf file is empty.
What is the reason for this problem?


$   slamdunk all -r ref.fa -b actb.bed -o output -rl 100 -mbq 15 -5 0 -mi 0.80 -mc 2 -mv 0.2 reads.fq

slamdunk all
Creating output directory: output
Creating output directory: output/map
Running slamDunk map for 1 files (1 threads)
.
Running slamDunk sam2bam for 1 files (1 threads)
.
Creating output directory: output/filter
Running slamDunk filter for 1 files (1 threads)
[E::idx_find_and_load] Could not retrieve index file for 'output/map/reads_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for 'output/filter/reads_slamdunk_mapped_filtered.bam'
.

Creating output directory: output/snp
Running slamDunk SNP for 1 files (1 threads)
.
Creating output directory: output/count
Running slamDunk tcount for 1 files (1 threads)
Wrong file type. Empty or not a vcf file.
.

**Comment by t-neumann** [comment]
That is fine, the test read file is actually only a very selected number of reads where you don't expect any SNPs to be called from

**Comment by Choopanian-Peyman** [comment]
Thank you, 
That is, there is not even one SNP  !!!?

**Comment by t-neumann** [comment]
Yeah its only an artificial readset of 12 reads for Unit-Tests

**Comment by Error-fre** [comment]
> There is one (probably not officially documented yet but it shows up in the help):
> 
> ```
>  -v VCFFILE, --vcf VCFFILE
>                         Skip SNP step and provide custom variant file.
> ```
> 
> I would merge all replicates for the variant calling and then supply a single vcf file for all samples.

When I used my no label samples as --vcf file the count does not change compared to the direct counting file from `slamdunk all`, shall I simply subtract the counting of the control sample from the labeled sample?

**Comment by t-neumann** [comment]
I think there is a misunderstanding - the VCF file typically comes from e.g. a WGS sequencing run where you called variants yourself. So you supply an actual VCF file and not a read set here
