### ISSUE TITLE
Index Files (*.bam.bai) Missing?

### ISSUE THREAD

**Issue by jvanbelzen** [t-neumann/slamdunk#110]
I'm trying to run slamdunk on fastq files in a directory.  I'm running it locally in an anaconda environment.

I'm getting an error about index files being missing from both the map and filter folders.  The problem persists even when I remove optional flags and use only the required input flags (-r -b -o [files]).  Strangely, the .bai files are missing from the map folder but are present in the filtered folder.  

As far as I can tell, the program still runs successfully and generates all outputs, but I'm not certain how to check that this is the case?  The map, filter, snp, count folders are present and all samples have an assigned output file, but how can I be sure that all reads were successfully mapped/analyzed?

**Terminal Input**
```
slamdunk all -r /Volumes/EasyStore/Sequencing_Workflow_Essentials/SLAMseq/S288C_reference_sequence_R64-3-1_20210421.fasta -b /Volumes/EasyStore/Sequencing_Workflow_Essentials/SLAMseq/YeastmRNA_BED.bed \
-o ../SLAMdunk/ -5 0 -n 10 \
-t 8 -m -rl 50 \
./*.fastq
```

**Terminal Output**
```
slamdunk all
Creating output directory: ../SLAMdunk/map
Running slamDunk map for 3 files (8 threads)
...
Running slamDunk sam2bam for 3 files (8 threads)
...
Creating output directory: ../SLAMdunk/filter
Running slamDunk filter for 3 files (8 threads)
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/map/B35-JV03_S14_R1_001_Trimmed_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/map/B35-JV01_S12_R1_001_Trimmed_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/map/B35-JV02_S13_R1_001_Trimmed_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/filter/B35-JV03_S14_R1_001_Trimmed_slamdunk_mapped_filtered.bam'
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/filter/B35-JV01_S12_R1_001_Trimmed_slamdunk_mapped_filtered.bam'
[E::idx_find_and_load] Could not retrieve index file for '../SLAMdunk/filter/B35-JV02_S13_R1_001_Trimmed_slamdunk_mapped_filtered.bam'


Creating output directory: ../SLAMdunk/snp
Running slamDunk SNP for 3 files (4 threads)
...
Creating output directory: ../SLAMdunk/count
Running slamDunk tcount for 3 files (8 threads)
...

...%
```

**Comment by t-neumann** [comment]
Hi,

that is actually fine and not a problem, it's a warning message from pysam actually, but index files are only required on the filtered bam files. Maybe I should someday work this out since those (harmless) messages pop up in many of my projects.

If you see some read counts in the `count` output files, you are all good

Cheers
