### ISSUE TITLE
ReadCount to get number of reads mapped?

### ISSUE THREAD

**Issue by my-linh-luu** [t-neumann/slamdunk#113]
Hello,

I have a question about the ReadCount column obtained in the TCcount CSV file. I thought I would get the number of reads that were mapped by summing all the read counts obtained. However, with this method, I get a higher number of reads than what was given initially with no multimap. Do you have any idea about this?

Thank you

**Comment by t-neumann** [comment]
I don't know what exactly you mean by "given intially with no multimap"?

One thing I can think of is that you have overlapping intervals in the bed file so reads are counted multiple times.

**Comment by my-linh-luu** [comment]
Hi, 
It was indeed an issue with our data.

Thank you.
