### ISSUE TITLE
Question about "-e" parameter

### ISSUE THREAD

**Issue by bocheng97** [t-neumann/slamdunk#115]
Hi,

I am dealing with quant-seq data, and I was wondering if I should use "-e" or not, also can you explain the description of "-e"  in the DOCS, "Deactivates NextGenMap’s SLAMSeq alignment settings. Can be used to align plain QuantSeq data instead of SLAMSeq data."? THank you

**Comment by t-neumann** [comment]
Hi,

if you have plain unlabelled QuantSeq data (no T>C conversions), then you should use -e to disable the alternative base scoring scheme we established for SLAM-seq data.
