### ISSUE TITLE
RuntimeError while executing command slamdunk map 

### ISSUE THREAD

**Issue by cz0430** [t-neumann/slamdunk#116]
Hi Tobias,
When I run the command "slamdunk map -r /path/BHK21genome.fa -o /path/map/ -n 1 -t 1 -ss /path/*, it generate the below error message:
Running slamDunk map for 11 files (1 threads)
Traceback (most recent call last):
  File "/path/bin/slamdunk", line 8, in <module>
    sys.exit(run())
  File "/path/lib/python3.6/site-packages/slamdunk/slamdunk.py", line 471, in run
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, outputDirectory, args.skipSAM)
  File "/path/lib/python3.6/site-packages/slamdunk/slamdunk.py", line 149, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/path/lib/python3.6/site-packages/slamdunk/dunks/mapper.py", line 107, in Map
    run("ngm -b -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/path/lib/python3.6/site-packages/slamdunk/utils/misc.py", line 196, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "ngm -b -r /path/BHK21genome.fa -q /path/Ctrl_1.clean.fq.gz -t 1 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l  --rg-id 0 --rg-sm Ctrl_1.clean.fq:pulse:0 -o /path/map/Ctrl_1.clean.fq_slamdunk_mapped.bam"

I tried to reinstall slamdunk under a new conda environment, it still generated the same error message. Could you let me know the possible reasons for such error and how caｎ　Ｉ　ｓｏｌｖｅ　ｉｔ？Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．　Ｌｏｏｋｉｎｇ　ｆｏｒｗａｒｄ　ｙｏｕｒ　ｒｅｐｌｙ．

Ｂｅｓｔ，　
Ｈｕａｎ

**Comment by t-neumann** [comment]
Hi - can you you send me also the content of the log files in the map folder?

**Comment by Umair1441** [comment]
I also got the sam error ..

here is my log file content in map folder...

b'[MAIN] NextGenMap 0.5.5\n'b'[MAIN] Startup : x64 (build Jul 15 2018 19:15:59)\n'b'[MAIN] Starting time: 2023-08-17.16:41:22\n'b'[CONFIG] Parameter:  --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --broken_pairs 0 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 1 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output output/map/NEA1_1_EKDL230012705-1A_HJKV3DSX7_L3_1.fq_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry NEA1_1_EKDL230012705-1A_HJKV3DSX7_L3_1.fq.gz --qry_count -1 --qry_start 0 --ref hg19/hg19.fa.gz --ref_mode -1 --rg_id 0 --rg_sm NEA1_1_EKDL230012705-1A_HJKV3DSX7_L3_1.fq:pulse:0 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 0 --update_check 0 --very_fast 0 --very_sensitive 0\n'b'[NGM] Opening for output (SAM): output/map/NEA1_1_EKDL230012705-1A_HJKV3DSX7_L3_1.fq_slamdunk_mapped.sam\n'b'[SEQPROV] Reading encoded reference from hg19/hg19.fa.gz-enc.2.ngm\n'b'[SEQPROV] Reading 3137 Mbp from disk took 5.93s\n'b'[PREPROCESS] Building reference table\n'b'[PREPROCESS] Allocated 1 hashtable units (tableLocMax=2^32.000000, genomeSize=2^31.546856)\n'b'[PREPROCESS] Building RefTable #0 (kmer length: 13, reference skip: 2)\n'b'[PREPROCESS] \tNumber of k-mers: 67108865\n'b'[PREPROCESS] \tCounting kmers took 90.86s\n'b'[PREPROCESS] \tAverage number of positions per prefix: 17.554293\n'b'[PREPROCESS] \tIndex size: 335544325 byte (67108865 x 5)\n'b'[PREPROCESS] \tGenerating index took 3.37s\n'b'Killed\n'
