### ISSUE TITLE
Correlation half-life calculation and DESeq2?

### ISSUE THREAD

**Issue by quarkaffi** [t-neumann/slamdunk#119]
Hi,

I was using the slam-seq pipeline and everything ran very smoothly. I did a pulse-chase experiment (24 labelling followed by a chase with 0h, 2h, 4h and 8h timpoints). I then did a differential gene expression analysis using DESeq2 comparing 8h vs 0h after the onset of the chase (using the readCount column for the sizefactor). I then went on to calculate the half-lives of all genes using the model described in another issue here. While my calculated half-lives correlate reasonably with other published datasets with pearson's correlations of 0.5-0.6 (I use another cell line so I assumed that this is reasonable), the correlation of my DESeq2 analysis and the half-lives is extremely poor (0.126).
![image](https://user-images.githubusercontent.com/83014485/196046882-87605067-88f7-4edd-88c3-91c1956fe8cf.png)
![image](https://user-images.githubusercontent.com/83014485/196046923-2e77045b-42ef-4ea1-9a41-b46f9c1d98ec.png)
![image](https://user-images.githubusercontent.com/83014485/196046932-2c8b2bd1-3578-46f1-9455-fe94daa698e7.png)

Shouldn't be the genes that are most negatively affected in the DESeq2 analysis also the ones that show the lowest half-life and vice versa, or am I missing something? Would it help if I use a more stringent counting cutoff (currently it is at the standard input of 1)? Or am I getting something completely wrong here and they shouldn't correlate? I am extremely puzzled by that outcome.

The read-length is 120, on average 50M reads per replicate (done in triplicates).

Best
Martin

**Comment by t-neumann** [comment]
Excellent summary from @isaacvock

You would not expect any genes to be changing by adding 4SU and watching them over time - that was the whole point why 4SU labelling was introduced, since it should not interfere with any cellular processes and the cell should remain in its default physiological state. So any log2FC you are reading out are either 4SU effects or anyhing other unwanted biases you introduce experimentally.

**Comment by quarkaffi** [comment]
Okay, I think I found what was off. The analysis just finished of my modified run. Yesterday I noted that there are quite some overlapping features in my 3UTR bedfile which presumable lead to regions being counted multiple times for different genes (and the same ones). The way that I collapsed these files was to sum up all the counts from the same transcript and went ahead with the downstream analysis (except for the conversion where I averaged it).

I got rid of all the ambiguous features and merged overlapping features (if they are coming from the same gene) into one and reran the analysis. Now everything correlates with almost the same Pearson's as in the paper of your lab! 

Thank you again for all the help and it was good to have that little sanity check as I was losing my mind in the last days.

**Comment by isaacvock** [comment]
I guess I'm still confused as to why the correlation would be identical, as I would expect nothing but negative L2FCs in your case whereas in that paper there is an even spread of positive and negative L2FCs (unless you are in fact enriching for s4U RNA, like TT-SLAM-seq? Or I am missing something about the normalization strategy). Anyways, I'm glad you were able to figure everything out, sorry for all of my misunderstandings!

**Comment by quarkaffi** [comment]
Yes, it is simply shifted. And you are right, the shape is still a bit more like a cone, however much better behaved.

No worries, it was my fault for not being clearer. Really appreciate all your input.
