### ISSUE TITLE
Genomic locations of the TC reads

### ISSUE THREAD

**Issue by aishwarya-gondane** [t-neumann/slamdunk#122]
Hi,

I was wondering if it is possible to fish out the exact genomic locations of the TC reads. For example, the transcript length is 800 bp and has 50 TCReadCount. Is it possible to know the exact location of these TCReads?

**Comment by t-neumann** [comment]
what you could do is use the `alleyoop read-separator` script that gives you separate bam files for labelled and unlabelled reads and you could take it from there

**Comment by aishwarya-gondane** [comment]
Hi Tobias,

Thanks for the suggestion. I have used the alleyoop read-separator module to get the TC Filtered BAM files and then converted them to bed files to look at the genomic locations. Is this the correct approach?
