### ISSUE TITLE
Downstream analysis

### ISSUE THREAD

**Issue by paurosales** [t-neumann/slamdunk#123]
Hi @t-neumann,

I'm using slamdunk to analyse paired-ended mRNA data (used the pertinent adjustments on the mapping step fo PE data). But I have some (rather basic) questions about DE analysis with `DESeq2`. I'm using both TcReadCount and ReadCount to run the `DESeq2()` function and then use:

`sizeFactors(ddsTcReadCount) <- sizeFactors(ddsReadCount)`

as described before in other issues, and use `ddsTcReadCount` for further analysis.  Are there any other particular steps for DE analysis I should do when using TcReadCount data?

Also for gene related results I'm collapsing counts with the same transcript ID by `sum()` and then match with the corresponding gene ID, and use that as input for `DESeq`. It shouldn't be a problem right?

Sorry if my questions are far from slamdunk itself :)

**Comment by t-neumann** [comment]
Hi - sounds all good to me what you are doing. Typically we also filter genes for a certain baseline expression in your control condition, but that's about it. Good luck!
