### ISSUE TITLE
How to interpret the bigwig values?

### ISSUE THREAD

**Issue by gdolsten** [t-neumann/slamdunk#127]
Hi, how do I calculate the values in the .bdg file? I converted the .bdg file, tcreadcount, and the basereadcount .bam files to bws, but I am not able to recreate the bw corresponding to the .bdg  from the bw files generated from the tcreadcount and basereadcount. Which one is the best to use for genome pileups?

**Comment by t-neumann** [comment]
Hi - sorry I need a bit more info. What files exactly did you produce using which command?
And what is your overall goal, what do you want to visualize, what is your scientific question?

**Comment by gdolsten** [comment]
I am trying to visualize the presence/absence of converted (nascent) and non-converted (mature) reads in IGV. To do this, I did two things in parallel: 1. first running alleyoop read-separator, and then running bamCoverage -bs 1 --effectiveGenomeSize on the bam files from read-separator ({filename}_backgroundReads.bam, {filename}_TCReads.bam). 2. I convert the .bedgraph file in /count/ to a .bw using bedGraphToBigWig. 

However, these approaches seem to yield different results, and I am not sure which one is better for visualization. For example, if I divide the values from {filename}_TCReads.bw by  {filename}_backgroundReads.bw, I do not get the same values as in the /counts/.bedgraph (which goes from 0 to 1)

**Comment by t-neumann** [comment]
Then you should use the bigwigs you create with bamCoverage on the TCReads and backgroundReads bam files.

The count/bedGraph files give you the conversion rates per T across the genome which are naturally [0,1] but dont give you any indication about converted / unconverted read counts
