### ISSUE TITLE
Effect of --slam-seq 2 parameter in NextGenMap call?

### ISSUE THREAD

**Issue by isaacvock** [t-neumann/slamdunk#128]
Hello @t-neumann,

I recently noticed that in SLAMDUNK's call to NextGenMap, it by default includes the parameter setting `--slam-seq 2`. I was unable to find any information about this parameter on the NextGenMap wiki or parameter documentation printed when calling `ngm` with no other options or input. The (fantastic) SLAMDUNK documentation mentions something about an altered scoring function, which sounds really useful so I wanted to see if you knew any more details about what this parameter option does? I recognize that this question is probably more appropriate for the NextGenMap folks, and I posted a similar question on their Github, but their is a lot less recent activity there than here so I thought I'd try both.

Thank you,
Isaac

**Comment by t-neumann** [comment]
Hi Isaac,

the --slam-seq 2 parameter introduces an adapted scoring matrix that does not penalize T>C mismatches as indicated in Table 1 of the Slamdunk paper. Hope that helps.

Tobi

**Comment by isaacvock** [comment]
Ah should've known to look there. Thank you very much!
