### ISSUE TITLE
Errors with Slamdunk Count / Alleyoop Utrrates

### ISSUE THREAD

**Issue by zaroogz** [t-neumann/slamdunk#137]
Hi there; as a preface, I am very new to bioinformatics, but I have had some issues in running the slamdunk count / alleyoop utrrate commands. When I put the following into my terminal, all that happens is that the terminal states "Running slamDunk tcount for 1 files (1 threads)" and spits out files with no data:

> slamdunk count -o Test-Files -r ccds.3utr.hg19.fasta -b ccds.3utr2.hg19-2.bed Test-Files/L001_R1_slamdunk_mapped_filtered.bam

The map/filter steps seemed to have run alright, but not sure why this may be the case. Additionally, when I try to use:

> alleyoop utrrates -o Test-Files -r ccds.3utr.hg19.fasta -t 1 -b ccds.3utr2.hg19-2.bed Test-Files/L001_R1_slamdunk_mapped_filtered.bam

the following is stated: 

> Running alleyoop utrrates for 1 files (1 threads)
/opt/homebrew/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/homebrew/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/opt/homebrew/bin/alleyoop", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slamdunk/alleyoop.py", line 530, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slamdunk/alleyoop.py", line 180, in runStatsRatesUTR
    stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
  File "/opt/homebrew/lib/python3.11/site-packages/slamdunk/dunks/stats.py", line 528, in statsComputeOverallRatesPerUTR
    callR(getPlotter("globalRatePlotter") + " -f " + f.name + " -O " + outputPDF, log, dry=printOnly, verbose=verbose)
  File "/opt/homebrew/lib/python3.11/site-packages/slamdunk/utils/misc.py", line 211, in callR
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/opt/homebrew/lib/python3.11/site-packages/slamdunk/plot/globalRatePlotter.R -f /var/folders/6l/0n_4k3l10518xkycy_rzs17rtc2n8k/T/tmpm_ojxl6c -O Test-Files/L001_R1_slamdunk_mapped_filtered_mutationrates_utr.pdf"

The log file for alleyoop states the following:

> Using 99 as maximum read length.
/opt/homebrew/lib/python3.11/site-packages/slamdunk/plot/globalRatePlotter.R -f /var/folders/6l/0n_4k3l10518xkycy_rzs17rtc2n8k/T/tmpm_ojxl6c -O Test-Files/L001_R1_slamdunk_mapped_filtered_mutationrates_utr.pdf
b'Error in library(getopt) : there is no package called \xe2\x80\x98getopt\xe2\x80\x99\n'b'Execution halted\n'

If you have any recommendations on where to go from here, it would be greatly appreciated! I can get you anything else you may need as well. Thank you.

**Comment by t-neumann** [comment]
Hi - first question, can you send me the successions of commands you used to get to the step, where you would like to call `alleyoop rates`? Second question, how did you install slamdunk? Via conda? Or are you running the Docker image?

**Comment by zaroogz** [comment]
The commands are as follows:

`slamdunk map -r /Users/zaroogz/Desktop/SLAMseq/ccds.3utr.hg19.fasta -o /Users/zaroogz/Desktop/SLAMseq /Users/zaroogz/Desktop/SLAMseq/L001_R1.fastq`

This runs to completion and yields a ~6.7GB bam file

`slamdunk filter -o /Users/zaroogz/Desktop/SLAMseq -b /Users/zaroogz/Desktop/ccds.3utr2.hg19-2.bed L001_R1_slamdunk_mapped.bam`

This runs to completion and yields a ~250MB bam file

`slamdunk snp -o /Users/zaroogz/Desktop/SLAMseq -r /Users/zaroogz/Desktop/SLAMseq/ccds.3utr.hg19.fasta L001_R1_slamdunk_mapped_filtered.bam`

Looking at the log of this now, it seems like it didn't run; the log reads:

> /bin/sh: varscan: command not found
[mpileup] 1 samples in 1 input files

`slamdunk count -o /Users/zaroogz/Desktop/SLAMseq -s L001_R1_slamdunk_mapped_filtered_snp.vcf -r /Users/zaroogz/Desktop/SLAMseq/ccds.3utr.hg19.fasta -b /Users/zaroogz/Desktop/ccds.3utr2.hg19-2.bed L001_R1_slamdunk_mapped_filtered.bam`

This then crashes and yields the initial error. 

For alleyoop, I'm trying to call UTR conversions. Also, for installing slamdunk, I had to use pip since conda was having difficulties installing it (not sure fully on the reason for this). I believe that I have been running all of this in the conda environment though. 

Let me know anything else you need, and I thank you again.

**Comment by t-neumann** [comment]
Yeah you should try to reinstall slamdunk in a fresh conda environment - with pip you just install the python core, but all the non-python dependencies will be missing.

**Comment by zaroogz** [comment]
When I try to create a new environment, this is what pops up:

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.0.1=0
  - slamdunk -> pandas[version='>=0.25.3'] -> __osx[version='>=10.9']

Your installed version is: 12.0.1

This is why I ended up taking the pip route since I couldn't get past this error even with help from others in the lab; any recommendations?

**Comment by zaroogz** [comment]
MacBook Pro (2020, M1); it seemed like others had issues with the M chip on Github / Slack Overflow, but couldn't find a fix that worked for me thus far. The other person that's working with me in the lab has an intel chip in their MacBook and didn't encounter this problem

**Comment by zaroogz** [comment]
I also installed VarScan into my conda environment and it seems that the slamdunk snp command is now running; will update you on where this takes me

**Comment by zaroogz** [comment]
So it looks like the snp command ran; it yielded a 3.5MB document. Despite this, count still yields empty tsv files.

**Comment by zaroogz** [comment]
So I have updates: 

- slamdunk now works in a conda environment!
- bad news is that it still yields the same errors for alleyoop utrrates and slamdunk count 
- alleyoop rates also yields a similar error now, but I generated this file earlier today (not sure where it came from)
[L001_R1_slamdunk_mapped_filtered_overallrates.csv](https://github.com/t-neumann/slamdunk/files/13383249/L001_R1_slamdunk_mapped_filtered_overallrates.csv)

It seems to not be able to generate the .pdf, but it can generate the .csv

**Comment by t-neumann** [comment]
Can u try to run it all in one go with `slamdunk all`?

**Comment by zaroogz** [comment]
Sounds good; I inputted the following:

`slamdunk all -r ccds.3utr.hg19.fasta -b ccds.3utr2.hg19-2.bed -o Work -5 12 -n 100 --skip-sam L001_R1.fastq`

Will update you in the AM when it finishes

**Comment by zaroogz** [comment]
I've tried a few things now, and the pipeline seems to run from beginning to end now. However, the tsv file that I receive shows 0s for all columns; any recommendations on fixing this?

**Comment by ZoeyYang912** [comment]
Hello,

I am having the same issue.

I run slamdunk all using docker

`sudo docker run -m 20g -v $(pwd):/data tobneu/slamdunk:v0.4.3 alleyoop utrrates -o /data/alleyooputrrates -r /data/slamdunk/Mus_musculus.GRCm39.dna.primary_assembly.fa -b /data/slamdunk/mm10.bed /data/slamdunk/filter/10_S4_1.fastq_slamdunk_mapped_filtered.bam /`

The tsv file generated also showed 0s for all columns. And when I run alleyooputrrates, it gives me this error:

> Running alleyoop utrrates for 1 files (1 threads)
/opt/conda/envs/slamdunk/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/opt/conda/envs/slamdunk/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/bin/alleyoop", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 530, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 180, in runStatsRatesUTR
    stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/dunks/stats.py", line 528, in statsComputeOverallRatesPerUTR
    callR(getPlotter("globalRatePlotter") + " -f " + f.name + " -O " + outputPDF, log, dry=printOnly, verbose=verbose)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 211, in callR
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmpxswajq_8 -O /data/alleyooputrrates/1_S1_1.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf"

Did you figure out how this can be fixed? Thanks.

**Comment by ZoeyYang912** [comment]
I think I have figured it out....
I would have to use exactly same version and same release of reference fasta and utr bed file to be able to generate .tsv with counts and run alleyoop utrrates.

For example, I was trying to align to mm39, I downloaded mm39 from Ensembl, and downloaded 3'utr bed file on release 33 of mouse genome. However, for some reason, the mm39 from Ensembl may not be release 33, and these two are not compatible in slamdunk. I switched to download release 33 reference genome sequence from Gencode and it worked.

**Comment by zaroogz** [comment]
@t-neumann All values are 0 except for the last two columns which are -1; this continues for every row. I will give Zoey's approach a try since I had similar issues with running alleyoop utrrates, but I got a .csv from alleyoop rates. Will update you on this when I correct this

**Comment by zaroogz** [comment]
So good news with slamdunk; correcting the fasta / bed files fixed and I'm getting usable data now. However, the alleyoop utrrates still seems to be failing for some reason. It seems like it's processing the data fine as I get a csv file with data, but it seems to freak out when it tries to create a pdf. Any suggestions on why this may be the case?

**Comment by ZoeyYang912** [comment]
> @ZoeyYang912 so everything is working for you now correct? @zaroogz Are you sure it's for all entries all 0s or just the first few ones?

Yes Slamdunk is working for me. Thanks!

**Comment by t-neumann** [comment]
@zaroogz I suspect there is still something not right with the conda environment. Can you try running the last step within the Docker container (tobneu/slamdunk:v0.3.4)?

**Comment by zaroogz** [comment]
Docker is not working on my device for some reason (it just says it's stopped upon download). Looking online, it says that I might need to upgrade my OS. Will try this and see if it helps

**Comment by zaroogz** [comment]
So I haven't been able to get passed the map step on docker; I'm running the following command:

`docker run --platform linux/amd64 -m 8g -v $(pwd):/data tobneu/slamdunk:v0.3.4 slamdunk all -r /data/HG38-1-Assembly -b /data/HG38-BED-FILE.bed -o /data/ -t 6 /data/L001_R1.fastq`

and I'm getting the following error:

Traceback (most recent call last):
  File "/usr/local/bin/slamdunk", line 11, in <module>
    load_entry_point('slamdunk==0.3.4', 'console_scripts', 'slamdunk')()
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 233, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/dunks/mapper.py", line 104, in Map
    run(getBinary("ngm") + " -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/utils/misc.py", line 190, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/usr/local/lib/python2.7/dist-packages/slamdunk/contrib/ngm -r /data/HG38-1-Assembly -q /data/L001_R1.fastq -t 6 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l  --rg-id 0 --rg-sm sample_0:NA:-1 -o /data/map/L001_R1_slamdunk_mapped.sam"

The sam file is nearly written, and then it crashes; not sure on the issue here.

**Comment by zaroogz** [comment]
Despite the above issue, `slamdunk count` works on Docker (although rather slowly). `alleyoop utrrates` also appears to be running at the moment; will update on this in the morning

**Comment by ZoeyYang912** [comment]
> So I haven't been able to get passed the map step on docker; I'm running the following command:
> 
> `docker run --platform linux/amd64 -m 8g -v $(pwd):/data tobneu/slamdunk:v0.3.4 slamdunk all -r /data/HG38-1-Assembly -b /data/HG38-BED-FILE.bed -o /data/ -t 6 /data/L001_R1.fastq`
> 
> and I'm getting the following error:
> 
> Traceback (most recent call last): File "/usr/local/bin/slamdunk", line 11, in load_entry_point('slamdunk==0.3.4', 'console_scripts', 'slamdunk')() File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 478, in run runAll(args) File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 233, in runAll runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM) File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 148, in runMap mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose) File "/usr/local/lib/python2.7/dist-packages/slamdunk/dunks/mapper.py", line 104, in Map run(getBinary("ngm") + " -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly) File "/usr/local/lib/python2.7/dist-packages/slamdunk/utils/misc.py", line 190, in run raise RuntimeError("Error while executing command: "" + cmd + """) RuntimeError: Error while executing command: "/usr/local/lib/python2.7/dist-packages/slamdunk/contrib/ngm -r /data/HG38-1-Assembly -q /data/L001_R1.fastq -t 6 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l --rg-id 0 --rg-sm sample_0:NA:-1 -o /data/map/L001_R1_slamdunk_mapped.sam"
> 
> The sam file is nearly written, and then it crashes; not sure on the issue here.

I had similar issue when running with Docker. I had to clean out all the files that slamdunk generated (like.fa.fai), and just leave the reference fasta, utr bed, and input fastq in the working directory, and run it again then it work. I tried it with one sample first and make sure the code works (slamdunk, alleyooputrrates etc) , and when I try to run for multiple samples in a batch, I had to clean out the files from the first run and rerun.

**Comment by t-neumann** [comment]
Is there anything written in the `map/*log` files?

**Comment by zaroogz** [comment]
Sorry for the delay on this as I've been on vacation. I've followed @ZoeyYang912 advice; however, 'alleyoop utrrates' doesn't still seem to work in Docker. I have attached the .csv, .pdf, and the .log here. When looking at conversion rates in my count file (after excluding utr's with no T coverage), I'm getting a general conversion rate of ~0.25% which is more or less expected. 

[L001_R1_slamdunk_mapped_filtered_mutationrates_utr.log](https://github.com/t-neumann/slamdunk/files/13506141/L001_R1_slamdunk_mapped_filtered_mutationrates_utr.log)
[L001_R1_slamdunk_mapped_filtered_mutationrates_utr.pdf](https://github.com/t-neumann/slamdunk/files/13506138/L001_R1_slamdunk_mapped_filtered_mutationrates_utr.pdf)
[L001_R1_slamdunk_mapped_filtered_mutationrates_utr.csv](https://github.com/t-neumann/slamdunk/files/13506139/L001_R1_slamdunk_mapped_filtered_mutationrates_utr.csv)

Also an additional question: I saw that a previous thread briefly discussed TruSeq vs QuantSeq for library prep. Both result in stranded data and thus should work based on the previous thread, but is there any advantages to using QuantSeq over TruSeq?

**Comment by t-neumann** [comment]
Hey @zaroogz - so if it didnt work on Docker, how did you get to the plots or what am I missing here?

TruSeq is full length transcript sequencing and Quantseq only sequences the 3'end of transcripts. The idea is that you can multiplex many more samples as you use up less reads per transcript. But of course you are blind to isoforms ending in the same 3' ends.

**Comment by zaroogz** [comment]
Apologies for not clarifying; it seems that the .csv file is working, but the .pdf graph seems to not show any utr T->C mutation rates despite looking at the count .tsv generated via `slamdunk count` and confirming that there are conversions occurring. The T to C conversions are also seem to be in a relative overabundance when glancing in IGV.
