### ISSUE TITLE
About calculating T>C reads CPM  

### ISSUE THREAD

**Issue by bioinformatica** [t-neumann/slamdunk#146]
Dear Neumann:

I tried to repeat Figure 3 and calculate the CPM value of T>C, which is about 100 times larger than the figure in the paper. I use R script for tcount.tsv, the calculation formula is TcReadCount_CPM = TcReadCount/sum(ReadCount)*1000000. Is there anything wrong?

![image](https://github.com/t-neumann/slamdunk/assets/24775272/9e5320e7-7444-4d61-b269-87d44ed9f3a0)

please kindly help.

**Comment by t-neumann** [comment]
Hi,

the axis ranges look roughly comparable to me, where do you see the 100-fold increase?

**Comment by t-neumann** [comment]
Did you download the original count files from the paper and repeat the plots using those tables, as sanity check?

**Comment by t-neumann** [comment]
I see you use only one replicate instead of all three. Maybe directly use the data from Supplementary Table S1 from the paper?

**Comment by t-neumann** [comment]
Did you compare the x and y axis with the ones from the supplemental table? I have the suspicion that you do not correct for no4SU treated samples as stated in there (Mean of all T>C Reads (CPM) (45min4SU - 0h 4SU)):

<img width="547" alt="image" src="https://github.com/t-neumann/slamdunk/assets/17272623/58de1237-ae76-40f9-8ec3-21aa6e61c467">
