### ISSUE TITLE
about pair-end data

### ISSUE THREAD

**Issue by bioinformatica** [t-neumann/slamdunk#147]
Dear Tobias:

My samples were sequenced by a sequencing company, and they used paired-end sequencing to obtain 1.fq and 2.fq. Can I use slamdunk all to analyze only one file, 1.fq, without processing the other file? I have read #57, this step is really difficult for me, I am a beginner in processing sequencing data.

best wishes!

**Comment by t-neumann** [comment]
Yes you can also simply use R1, that should give you reasonable results
