### ISSUE TITLE
My slam-seq sequencing data only has 60-70% reads mapped to the genome

### ISSUE THREAD

**Issue by bioinformatica** [t-neumann/slamdunk#150]
Dear Tobias:

My slam-seq sequencing data only has 60-70% reads mapped to the genome. Is this normal? How to improve? I saw that 91% of the work you published.

The following is my command line and log:
slamdunk all  -r /Data/hg38.fa    -t 60  -n 100  -b /Data/3utr-ucsc-v45.bed  -o /Data/dunk   /Data/*_1_R1.fq.gz

[MAIN] Done (3275776 reads mapped (67.49%), 1577827 reads not mapped, 5727857 lines written)

Best

**Comment by t-neumann** [comment]
No we typically have >90% mapped as you point out

**Comment by t-neumann** [comment]
Yes we typically run cutadapt, but other than that, you should be good to go. 80% doesn't sound too bad
