### ISSUE TITLE
pip install fails on 0.2.4

### ISSUE THREAD

**Issue by datakid** [t-neumann/slamdunk#17]
I tried to pip install using py2.7 and py3.4. Both failed with:

>  Running setup.py (path:/tmp/user/0/pip-build-zn7jtiz2/slamdunk/setup.py) egg_info for package slamdunk
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/user/0/pip-build-zn7jtiz2/slamdunk/setup.py", line 38, in <module>
        execfile(path.join(here, name, 'version.py'))
    NameError: name 'execfile' is not defined

This occurred on both CentOS 7.3 and Debian Testing

**Comment by datakid** [comment]
I made a mistake. Works with Py2 on both machines. I have set py3 to be default and had forgotten that important fact. 

There are instructions for [how to replace execfile in python3 all over SO](https://stackoverflow.com/questions/6357361/alternative-to-execfile-in-python-3).

**Comment by t-neumann** [comment]
Yeah there's still some more python3 dependencies in there that need more refactoring. Currently python2.7 is the only option but we're definitely aiming for python3 support in future releases.

**Comment by yashad-samant** [comment]
Is it now working on py3?

**Comment by t-neumann** [comment]
Can you paste the error you're getting?

You might also consider switching to the Docker container.

**Comment by yashad-samant** [comment]
NameError: name 'execfile' is not defined

I can definitely work on docker installation. But I am documenting this for a relatively new person to linux and software. It might be a little bit overwhelming

**Comment by t-neumann** [comment]
Ok yeah we're definitely planning to look into this, but that's not happening anytime soon since there's other stuff to attend to first.

So you're best bet for now is to either move to python2.7 or use Docker.

**Comment by yashad-samant** [comment]
Thanks Tobias for swift response. I will look into it.
