### ISSUE TITLE
Map function not working

### ISSUE THREAD

**Issue by iyloh** [t-neumann/slamdunk#29]
Hello,

I thought I had successfully installed SlamDunk, but it seems that the map function is not working. I got the following error when trying to run "slamdunk all":

```
slamdunk all -r /Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -b /Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/mm10_3UTR.bed -o slamdunkout test.fq
Traceback (most recent call last):
  File "/Users/inezoh/virtual/bin/slamdunk", line 11, in <module>
    sys.exit(run())
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 234, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 149, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/dunks/mapper.py", line 104, in Map
    run(getBinary("ngm") + " -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/utils/misc.py", line 191, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/contrib/ngm -r /Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -q test.fq -t 1 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l  --rg-id 0 --rg-sm sample_0:NA:-1 -o slamdunkout/map/test_slamdunk_mapped.sam"
```

To try and narrow down the source of the error, I ran "slamdunk map" and got this error:

```
slamdunk map -r /Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -o mapout test.fq
Traceback (most recent call last):
  File "/Users/inezoh/virtual/bin/slamdunk", line 11, in <module>
    sys.exit(run())
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 414, in run
    mapper.checkNextGenMapVersion()
  File "/Users/inezoh/virtual/lib/python2.7/site-packages/slamdunk/dunks/mapper.py", line 43, in checkNextGenMapVersion
    raise RuntimeError('Could not get NextGenMap version. Please reinstall slamdunk package.')
RuntimeError: Could not get NextGenMap version. Please reinstall slamdunk package.
```

I have uninstalled and reinstalled slamdunk, but ran into the same problem.

**Comment by t-neumann** [comment]
Hi,

how did you install slamdunk and what version?

And second, what output does 

slamdunk/slamdunk/contrib/ngm -v

give you vs what does the slamdunk/slamdunk/version.py file say?

**Comment by iyloh** [comment]
I installed version 0.2.4 using `pip install slamdunk`.

`slamdunk/slamdunk/contrib/ngm -v` gives me:
`-bash: slamdunk/slamdunk/contrib/ngm: No such file or directory`

In the slamdunk/slamdunk/version.py file, the required NextGenMap version is 0.5.2.

**Comment by t-neumann** [comment]
Looks like NextGenMap was not properly installed. Can you check whether the Symlink slamdunk/slamdunk/contrib/ngm actually exists? Should point to something like nextgenmap/bin/ngm-0.5.2/ngm

**Comment by iyloh** [comment]
It looks like the symlink does not exist so I think you are right that NextGenMap did not install properly for some reason. I just gained access to a cluster so I went ahead and installed SlamDunk from source so I could see if each component was being built properly. I received the following warnings when I was building NextGenMap:

`/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/index/BamStandardIndex_p.cpp: In member function ‘void BamTools::Internal::BamStandardIndex::WriteLinearOffsets(const int&, BamTools::Internal::BaiLinearOffsetVector&)’:
/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/index/BamStandardIndex_p.cpp:958: warning: comparison between signed and unsigned integer expressions`

`/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendGetRequest(size_t)’:
/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/BamHttp_p.cpp:409: warning: comparison between signed and unsigned integer expressions
/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/BamHttp_p.cpp: In member function ‘bool BamTools::Internal::BamHttp::SendHeadRequest()’:
/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/BamHttp_p.cpp:501: warning: comparison between signed and unsigned integer expressions`

`/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/TcpSocket_p.cpp: In member function ‘std::string BamTools::Internal::TcpSocket::ReadLine(int64_t)’:
/home/iyoh/slamdunk/slamdunk/contrib/nextgenmap/lib/bamtools-2.3.0/src/api/internal/io/TcpSocket_p.cpp:336: warning: comparison between signed and unsigned integer expressions`

I'm not sure if that is the source of the error. When I tried the map function again, I got a different error from the pip-installed slamdunk:

`./slamdunk map -r /Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa -o ~/test/ /Users/inezoh/virtual/test.fq 
Creating output directory: /home/iyoh/test/
Running slamDunk map for 1 files (1 threads)
['/Users/inezoh/seqtools/genomes/Mus_musculus/UCSC/mm10/Sequence/WholeGenomeFasta/genome.fa', '/Users/inezoh/virtual/test.fq'] ['/home/iyoh/test/test_slamdunk_mapped.bam']
Traceback (most recent call last):
  File "./slamdunk", line 28, in <module>
    slamdunk.run()
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 436, in run
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, outputDirectory, args.skipSAM)
  File "/home/iyoh/slamdunk/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/home/iyoh/slamdunk/slamdunk/dunks/mapper.py", line 101, in Map
    if(checkStep([inputReference, inputBAM], [replaceExtension(outputSAM, ".bam")], force)):
  File "/home/iyoh/slamdunk/slamdunk/utils/misc.py", line 150, in checkStep
    raise RuntimeError("One or more input files don't exist.")
RuntimeError: One or more input files don't exist.`

**Comment by t-neumann** [comment]
Are any files created in the output directory?

**Comment by iyloh** [comment]
I realized that the last error I got was because I didn't have my reference and sample files in the right folder (sorry about the confusion!). 

But I re-ran slamdunk with the files in the right place and I'm back to getting the original error message. The output directory contains an empty "test_slamdunk_mapped.sam" file and a "test_slamdunk_mapped.log" file. The log file says this:

[MAIN] NextGenMap 0.5.2
[MAIN] Startup : x64 (build May 30 2018 16:22:54)
[MAIN] Starting time: 2018-05-31.13:36:49
[CONFIG] Parameter:  --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 1 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output /home/iyoh/test/test_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry /home/iyoh/test.fq --qry_count -1 --qry_start 0 --ref /home/iyoh/genome.fa --ref_mode -1 --rg_id 0 --rg_sm sample_0:NA:-1 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 12 --update_check 0 --very_fast 0 --very_sensitive 0
[NGM] Opening for output (SAM): /home/iyoh/test/test_slamdunk_mapped.sam
[SEQPROV] Encoding reference sequence.
[SEQPROV] Size of reference genome 2725 Mbp (max. 17179 Mbp)
[SEQPROV] Allocating 1362780352 (2780048573) bytes for the reference.
[SEQPROV] BinRef length: 1362780340ll (elapsed 13.313368)
[SEQPROV] 0 reference sequences were skipped (length < 10).
[SEQPROV] Writing encoded reference to /home/iyoh/genome.fa-enc.2.ngm
[SEQPROV] Writing to disk took 2.16s
[PREPROCESS] Building reference table
[PREPROCESS] Allocated 1 hashtable units (tableLocMax=2^32.000000, genomeSize=2^31.343906)
[PREPROCESS] Building RefTable #0 (kmer length: 13, reference skip: 2)
[PREPROCESS]    Number of k-mers: 67108865
[PREPROCESS]    Counting kmers took 58.73s
[PREPROCESS]    Average number of positions per prefix: 16.251629
[PREPROCESS]    Index size: 335544325 byte (67108865 x 5)
[PREPROCESS]    Generating index took 2.79s
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by iyloh** [comment]
I had about 80GB of memory free at the time I was attempting the run.

________________________________

**Comment by t-neumann** [comment]
Do you have any set resource constraints? Like a scheduling system or a Docker machine?

**Comment by iyloh** [comment]
Apparently I did have resource constraints that I was previously unaware of. Thanks for your patience! I think I have the map function working now, although I only see a BAM file and a log file in the output directory. Should I also be expecting a BAM index file to have been generated? I know I can generate one from the BAM file, but wanted to make sure that this wasn't a sign that I still don't have the map function working properly.

________________________________
