### ISSUE TITLE
Downloading w/ pip

### ISSUE THREAD

**Issue by ayearley** [t-neumann/slamdunk#32]
Hi, I have been trying to use the pip install command to download slamdunk onto my linux computer. I keep getting this error below and my install aborts. Any assistance would be greatly appreciated.

Collecting slamdunk
  Downloading https://files.pythonhosted.org/packages/b1/66/1d6f6e176e5bc6b2fde124a0fa1fd12e7fbe17011e607aaaf4ccb517f5a2/slamdunk-0.3.0.tar.gz (18.8MB)
    100% |████████████████████████████████| 18.8MB 91kB/s 
Requirement already satisfied: Cython>=0.20.1 in ./.local/lib/python2.7/site-packages (from slamdunk)
Requirement already satisfied: biopython>=1.63 in ./.local/lib/python2.7/site-packages (from slamdunk)
Requirement already satisfied: intervaltree>=2.1.0 in ./.local/lib/python2.7/site-packages (from slamdunk)
Requirement already satisfied: joblib>=0.9.4 in ./.local/lib/python2.7/site-packages (from slamdunk)
Requirement already satisfied: pandas>=0.13.1 in ./.local/lib/python2.7/site-packages (from slamdunk)
Collecting pybedtools>=0.6.4 (from slamdunk)
  Downloading https://files.pythonhosted.org/packages/09/57/e7668e8644c60413be05b8cc9c23aaea3a0717b4025843d8c26b7c4822af/pybedtools-0.7.10.tar.gz (12.6MB)
    100% |████████████████████████████████| 12.6MB 137kB/s 
Requirement already satisfied: pysam>=0.8.3 in ./.local/lib/python2.7/site-packages (from slamdunk)
Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from biopython>=1.63->slamdunk)
Requirement already satisfied: sortedcontainers in ./.local/lib/python2.7/site-packages (from intervaltree>=2.1.0->slamdunk)
Requirement already satisfied: pytz>=2011k in ./.local/lib/python2.7/site-packages (from pandas>=0.13.1->slamdunk)
Requirement already satisfied: python-dateutil>=2.5.0 in ./.local/lib/python2.7/site-packages (from pandas>=0.13.1->slamdunk)
Requirement already satisfied: six in ./.local/lib/python2.7/site-packages (from pybedtools>=0.6.4->slamdunk)
Installing collected packages: pybedtools, slamdunk
  Running setup.py install for pybedtools ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9T9PXY/pybedtools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VyZoft-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/parallel.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/__main__.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/filenames.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/stats.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/__init__.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/logger.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/version.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/settings.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/genome_registry.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/bedtool.py -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/helpers.py -> build/lib.linux-x86_64-2.7/pybedtools
    creating build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/__init__.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_len_leak.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_contrib.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/tfuncs.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_helpers.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_gzip_support.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_iter.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/regression_tests.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_scripts.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test_cbedtools.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    copying pybedtools/test/test1.py -> build/lib.linux-x86_64-2.7/pybedtools/test
    creating build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/intersection_matrix.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/long_range_interaction.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/plotting.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/__init__.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/classifier.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/bigbed.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/venn_maker.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    copying pybedtools/contrib/bigwig.py -> build/lib.linux-x86_64-2.7/pybedtools/contrib
    creating build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/intersection_matrix.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/annotate.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/venn_gchart.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/__init__.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/py_ms_example.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/intron_exon_reads.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/peak_pie.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    copying pybedtools/scripts/venn_mpl.py -> build/lib.linux-x86_64-2.7/pybedtools/scripts
    creating build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/__init__.py -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/dm3-chr2L-5M-invalid.gff.gz -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/tag_test1.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/v.vcf -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/small.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/a.igv_script -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/b.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/a.links.html -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/bedpe2.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/a.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.othersort.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.1.100.bam.bai -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/test_bedpe.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/x.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/y.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/CTCF_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/x.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/vcf-stderr-test.vcf -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.50.200.bam.bai -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/164.gtf -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/CTCF_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/hg19.gff -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/exons.gff -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/dm3-chr2L-5M.gff.gz -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/Cp190_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/1000genomes-example.vcf -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/rmsk.hg18.chr21.small.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/venn.b.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/c.gff -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/reads.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/snps.bed.gz -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/vcf-stderr-test.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/test.fa -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/rmsk.hg18.chr21.small.bed.gz -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/venn.c.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/tag_test2.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/d.gff -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/bedpe.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/issue_121.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.50.200.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/test_tsses.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/Cp190_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/hg38-problem.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/m1.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/test.fa.fai -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.sorted.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/democonfig.yaml -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/test_peaks.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/mm9.bed12 -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/SuHw_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/small.fastq -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/BEAF_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.gff.gz -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/SuHw_Mbn2_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.gff -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.sorted.bam.bai -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/BEAF_Kc_Bushey_2009.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/gdc.1.100.bam -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/multibamcov_test.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/expand_test.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/test/data/hg38-base.bed -> build/lib.linux-x86_64-2.7/pybedtools/test/data
    copying pybedtools/cbedtools.pyx -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/_Window.pyx -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/featurefuncs.pyx -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/cbedtools.pxd -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/featurefuncs.cxx -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/cbedtools.cxx -> build/lib.linux-x86_64-2.7/pybedtools
    copying pybedtools/_Window.c -> build/lib.linux-x86_64-2.7/pybedtools
    running build_ext
    building 'pybedtools.cbedtools' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/pybedtools
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-nbjU53/python2.7-2.7.15~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/ -I/usr/include/python2.7 -c src/gzstream.cpp -o build/temp.linux-x86_64-2.7/src/gzstream.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from src/gzstream.cpp:29:0:
    src/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
     #include <zlib.h>
              ^~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9T9PXY/pybedtools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-VyZoft-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9T9PXY/pybedtools/

**Comment by t-neumann** [comment]
Looks like you're missing the zlib. You cannot compile anything that requires gzip support - try installing it like this.

sudo apt-get install libz-dev

Alternatively, use our Docker container that works out of the box:

docker pull tobneu/slamdunk

**Comment by ayearley** [comment]
Hi, thank you for getting back to me. I did that but am now getting this error:

Traceback (most recent call last):
  File "/home/floyd/miniconda3/bin/slamdunk", line 11, in <module>
    load_entry_point('slamdunk==0.3.0', 'console_scripts', 'slamdunk')()
  File "/home/floyd/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/floyd/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/floyd/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/floyd/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/floyd/miniconda3/lib/python3.6/site-packages/slamdunk/slamdunk.py", line 34, in <module>
    from dunks import tcounter, mapper, filter, deduplicator, snps
ModuleNotFoundError: No module named 'dunks'

**Comment by t-neumann** [comment]
@ayearley 
Conda support is now enabled:

http://bioconda.github.io/recipes/slamdunk/README.html

conda create --name myenv -c bioconda slamdunk
