### ISSUE TITLE
One or more input files don't exist error

### ISSUE THREAD

**Issue by ayearley** [t-neumann/slamdunk#33]
I have been trying to run the all command with fq files as input, and I keep getting an input doesn't exist error even though these files do exist....

docker run -m 8g -v $(pwd):/data tobneu/slamdunk slamdunk all -r /Users/Downloads/hg38.fa -b /Users/Downloads/UTR\ annotations.bed -o /Users/Desktop/SLAM -5 12 -n 100 -m -mv .2 -mbq 27 --skip-sam files /Users/Desktop/OCI_AML-3_JQ1_rep-1_trimmed.fq.gz /Users/Desktop/OCI_AML-3_DMSO_rep-1_trimmed.fq.gz
slamdunk all
Creating output directory: /Users/Desktop/SLAM
Creating output directory: /Users/Desktop/SLAM/map
Running slamDunk map for 3 files (1 threads)
['/Users/Downloads/hg38.fa', 'files'] ['/Users/Desktop/SLAM/map/files_slamdunk_mapped.bam']
Traceback (most recent call last):
  File "/usr/local/bin/slamdunk", line 11, in <module>
    load_entry_point('slamdunk==0.3.0', 'console_scripts', 'slamdunk')()
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 233, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/dunks/mapper.py", line 101, in Map
    if(checkStep([inputReference, inputBAM], [replaceExtension(outputSAM, ".bam")], force)):
  File "/usr/local/lib/python2.7/dist-packages/slamdunk/utils/misc.py", line 150, in checkStep
    raise RuntimeError("One or more input files don't exist.")
RuntimeError: One or more input files don't exist.

**Comment by t-neumann** [comment]
Hm looks like you didn't mount /Users/Downloads/ and related directories anywhere.
What you're doing is mounting your current working directory on /data.

You need to get the mounting right. To have access to at least all files in your current working directory, you can do stuff like this:

-v $(pwd):$(pwd) -w $(pwd)

**Comment by ayearley** [comment]
But isn't that what "docker run -m 8g -v $(pwd):/data tobneu/slamdunk slamdunk" does? Would "-v $(pwd):$(pwd) -w $(pwd)" need to be executed in a different command before running slamdunk?

**Comment by t-neumann** [comment]
yes that's correct.

but you also need to set all the paths for your slamdunk command then to /data

Did you do that as well?

**Comment by abzzram** [comment]
Had the same error and fixing the mounting did the trick!

**Comment by t-neumann** [comment]
Great!
