### ISSUE TITLE
Alleyoop Dedup is truncating output files

### ISSUE THREAD

**Issue by swbarnes2** [t-neumann/slamdunk#35]
picard's Validate Sam File is seeing no problem with the files coming out of the slamdunk filter step, but putting those through dedup results in output bams that "have a defective last gzip block" which also causes the indexing of the bam to fail.  slamdunk and alleyoop v 0.2.4.  bam inputs and outputs of other slamdunk steps is fine.

**Comment by t-neumann** [comment]
Hi @swbarnes2 

I'm currently on vacation, but I'll look into it once I'm back end of next week.

**Comment by t-neumann** [comment]
Alright thanks for pointing this out, indeed the dedup process did not properly close the bam file handle which caused this error. I will include it in the next version release with a couple of other fixes. Do you need it urgently?

**Comment by t-neumann** [comment]
Fixed with v0.3.3
