### ISSUE TITLE
count :  ValueError: no sequence/region supplied.

### ISSUE THREAD

**Issue by haiyueliu** [t-neumann/slamdunk#36]
Hi, 
When I ran slamdunk count, I came to this error:
ValueError: no sequence/region supplied.

The detailed error info is : 

    180         # Retreive reference sequence
    181         region = utr.chromosome + ":" + str(utr.start + 1) + "-" + str(utr.stop)
    182         
    183         if(utr.chromosome in list(referenceFile.references)):
    184             #print(refRegion,file=sys.stderr)
--> 185             refSeq = referenceFile.fetch(region=region).upper()
        refSeq = undefined
        referenceFile.fetch = <built-in method fetch of pysam.libcfaidx.FastaFile object>
        region = 'chr1:70009-70108'

I did not know how this come?  Is there any clue what is the problem? Thanks a lot.

Best,
Haiyue

**Comment by t-neumann** [comment]
Looks like it's a bed file issue.

Can you send it over? Which species are you working on?

**Comment by haiyueliu** [comment]
I am working with human genome. The bed file that i used it like this:

![image](https://user-images.githubusercontent.com/27951511/45505541-1ecfb280-b78d-11e8-8ccc-9c84072fc9f3.png)

**Comment by t-neumann** [comment]
Could you send over the entire file?

I'll run a test around next week (on vacation currently)

**Comment by t-neumann** [comment]
Hi @haiyueliu 

this fast changes of the pysam versions are really a pain. I just fixed several bugs to support both newer and older pysam versions about a month ago.

In general, I would advise you to use slamdunk out of a conda environment (slamdunk is on bioconda) or use the Docker container (or build a Singularity image from it).
