### ISSUE TITLE
No conversion rates

### ISSUE THREAD

**Issue by abzzram** [t-neumann/slamdunk#42]
I ran ''slamdunk all' and then followed the instructions for the 'alleyoop utrrates' (the 'sanity check' part in the documentation). Looking at the PDF outputs, I found no conversions unfortunately. 
I added 4-thiouracil to my samples and extracted RNA after 30 mins (followed by Iodoacetamide treatment). Is it possible that I processed my data incorrectly or can I say that 30mins is just not enough time to detect conversions. 
My conditions were:
0um 4-thiouracil
100um 4-thiouracil
200um 4-thiouracil
400um 4-thiouracil

I'm _very_ new to RNAseq and just followed all the instructions on the documentation, so could I have just uploaded the wrong 3'UTR bed file or something? 

Best,
Ram

**Comment by t-neumann** [comment]
Hi @abzzram ,

sorry this issue got totally lost and I just found it now.
So with regards to your question - could you show me what the PDF actually shows? 30 mins sounds a bit short to me, but I am no wet-lab person, so take this with a graind of sand.

What species did you do this on and which fasta/bed files did you supply?

**Comment by abzzram** [comment]
Thanks for getting back to me. 
I've emailed you the the PDF files that show the conversion rates after the "alleyoop utrrates" command.
The genome I used was hg38. I've also attached the raw reads, genome, and 3' UTR bed file that I used. And I did the experiment using MCF 10A mamm


ary epithelial cells

To get the 3' UTR bed file, I followed the instructions given [here](https://groups.google.com/a/soe.ucsc.edu/forum/#!topic/genome/7V5j51XYUBQ). 


Here's the slamdunk all and alleyoop command I used: 
`slamdunk all -r GRCh38_fasta/GRCh38.primary_assembly.genome.fa -b 3PrimeUTR/GRCh383PUTR.bed -o output -rl 100 -mbq 27 -5 0 raw_reads/JAARJB01_S198_L006_R1_001.fastq.gz raw_reads/JAARJB02_S199_L006_R1_001.fastq.gz raw_reads/JAARJB03_S200_L006_R1_001.fastq.gz raw_reads/JAARJB04_S201_L006_R1_001.fastq.gz
`
`alleyoop utrrates -o output -r GRCh38_fasta/GRCh38.primary_assembly.genome.fa -t 1 -b 3PrimeUTR/GRCh383PUTR.bed -l 100 output/filter/JAARJB01_S198_L006_R1_001.fastq_slamdunk_mapped_filtered.bam output/filter/JAARJB02_S199_L006_R1_001.fastq_slamdunk_mapped_filtered.bam output/filter/JAARJB03_S200_L006_R1_001.fastq_slamdunk_mapped_filtered.bam output/filter/JAARJB04_S201_L006_R1_001.fastq_slamdunk_mapped_filtered.bam`

I also tried using a longer max read length of 500 and still didn't see any difference. 


Thank you so much for your help!

**Comment by yquint21** [comment]
Hi, 
I'm currently trying to analyze slamseq data and I'm running into the same problem. The PDFs that Alleyoop utrrates generates show no conversions: 
![image](https://github.com/t-neumann/slamdunk/assets/134380648/35daed26-205e-4081-9394-39ff4676cde9)

Although the Alleyoop rates pdfs do show some results:
![image](https://github.com/t-neumann/slamdunk/assets/134380648/baf82d1b-d970-45f2-a1d7-0fe6e6ec6bb1)


When checking the tcount.tsv file, (almost) all of the '3 UTR regions have a 0 TcReadCount: 

#slamdunk v0.4.3	3	sample info:	Z2_24h_r1	2	dTAG	NA
#annotation:	GSE100708_hg38_refseq_062016_ensemblv84_3UTR.bed	a16c41aeea3e57cab1edc2854231831f
Chromosome	Start	End	Name	Length	Strand	ConversionRate	ReadsCPM	Tcontent	CoverageOnTs ConversionsOnTs	ReadCount	TcReadCount	multimapCount	ConversionRateLower	ConversionRateUpper
chr22	29442122	29442455	5988	333	+	0	0	112	0	0	0	0	0	-1.0	-1.0
chr19	13961529	13962694	5989	1165	-	0.0	0.44048760411597493	242	56	0	9	0	0	-1.0	-1.0
chr12	109448654	109451813	83892	3159	-	0	0	921	0	0	0	0	0	-1.0	-1.0
chr12	109456117	109456313	83892	196	-	0	0	57	0	0	0	0	0	-1.0	-1.0
chr12	109457629	109457682	83892	53	-	0	0	10	0	0	0	0	0	-1.0	-1.0
chr12	109457991	109458078	83892	87	-	0	0	20	0	0	0	0	0	-1.0	-1.0
chr12	109460635	109460805	83892	170	-	0	0	31	0	0	0	0	0	-1.0	-1.0
chr12	109469514	109469728	83892	214	-	0	0	35	0	0	0	0	0	-1.0	-1.0
chr12	109477259	109477544	83892	285	-	0	0	53	0	0	0	0	0	-1.0	-1.0
chr7	74231501	74232105	5982	604	-	0	0	138	0	0	0	0	0	-1.0	-1.0
chr13	33836295	33837507	5983	1212	+	0	0	467	0	0	0	0	0	-1.0	-1.0
chr13	33966125	33966558	5983	433	+	0	0	140	0	0	0	0	0	-1.0	-1.0
chr6	111299030	111300015	5980	985	-	0.0	0.39154453699197767	385	133	0	8	0	0	-1.0	-1.0
chr4	39287448	39288760	5981	1312	-	0	0	431	0	0	0	0	0	-1.0	-1.0
chr17	82047901	82048725	5986	824	-	0	0	158	0	0	0	0	0	-1.0	-1.0
chr6	28903001	28904069	5987	1068	-	0.0	0.09788613424799442	337	22	0	2	0	0	-1.0	-1.0
chr6_GL000250v2_alt	168585	169653	5987	1068	-	0	0	0	0	0	0	0	0	-1.0	-1.0

The experiment was performed on K562 cells and I used hg38 as the reference genome. For the  3'UTR regions I have used the GSE100708_hg38_refseq_062016_ensemblv84_3UTR.bed file which I downloaded from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100708. 

See below the parameters I set for running slamdunk all and alleyoop utrrates. 

`slamdunk all -r "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/genome/hg38.fa" -b "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/GSE100708_hg38_refseq_062016_ensemblv84_3UTR.bed" -o "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20230523_results_subset/" -t 25 -5 12 -rl 100 -n 100 -m -mv 0.2 -c 2 "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/sample_file_subset.tsv" `

`alleyoop` utrrates -o "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20230523_alleyoop_scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/genome/hg38.fa" -b "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK00708_hg38_refseq_062016_ensemblv84_3UTR.bed" -l 100 "/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20230523_reilter/2932F15_merged_211011_D00404_0549_ACDANPANXX_TAATGCGC-CAGGACGT_L001_R1_001_trimmed.fastq_slamdunk_mapped_filtered.byquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20230523_results_subset/filter/2932F16_merged_211011_D00404_0549_ACDANPANXCTGAC_L001_R1_001_trimmed.fastq_slamdunk_mapped_filtered.bam" `"/scratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20_subset/filter/2932F1_merged_211011_D00404_0549_ACDANPANXX_CTGAAGCT-TATAGCCT_L001_R1_001_trimmed.fastq_slamdunk_mapped_fiscratch/yquint/ZEB_project/SLAM-seq/SLAM-DUNK_analysis/20230523_results_subset/filter/2932F2_merged_211011_D00404_0549_ACGCT-ATAGAGGC_L001_R1_001_trimmed.fastq_slamdunk_mapped_filtered.bam"`

Any help or suggestions would be very welcome

**Comment by t-neumann** [comment]
Hi,

indeed it seems like you have very low conversion rates. May I ask how long did you label?
I don't see any apparent mistake in your commands - the reasons that utrrates shows mostly zero is because from what I remember I plot the median mutation rates in the UTRs which at very low conversion rates converges to 0 (which you see already in the rates plot).
Can you maybe filter the table for UTRs that DO contain some reads (I see mostly UTRs without any reads) and check how the % of tc-reads looks there as sanity check?

**Comment by yquint21** [comment]
Thank you for your fast reply, I'm sorry it took some time to answer you. 
I discovered what went wrong with the analysis. The slam-seq data I'm using is from a collaboration and they used the TruSeq library preparation kit. Quant-seq produces sense reads while TruSeq produces antisense reads. I reverse complemented my reads, which fixed the issue (I got conversion rates). 

However, now that I figured this out I have some new questions. 
- Do you perhaps know if I can use slamdunk for analyzing this TruSeq slam-seq data?
- If so, are there things I should be aware of or change when doing the slamdunk analysis with this TruSeq data. For example should I still filter for only 3'UTR or should I include also exons and introns? 
- And a totally different question. In the original paper it is stated in the methods that "For gene-level analysis, raw reads mapped to different UTR annotations of the same 
gene were summed up by Entrez Gene ID". When analyzing RNA-seq data, for gene-level analysis I would normally select for the gene transcript with the highest read counts. Is there a specific reason why you choose for summing up the reads mapped to 3'UTR  regions of the same gene?

**Comment by t-neumann** [comment]
Hi @yquint21,

is Truseq data stranded? If yes, you should be able to use it.
Since slamdunk does not have a splice-aware mapper underneath, I would still advise you to only quantify reads in the 3' UTRs, though.

Regarding your last question - we are currently doing it like you state, i.e. select the transcript with the highest read counts and move from there. Back then we were not sure about the 3' end annotation so we decided to collect everything we could per gene, but quantifying only the dominant isoform for sure is more accurate.

**Comment by yquint21** [comment]
Yes, TruSeq is stranded. Thank you!!
