### ISSUE TITLE
failed to install the slamdunk via the server

### ISSUE THREAD

**Issue by kunUCSD** [t-neumann/slamdunk#43]
Dear there,

I'm trying to install the slamdunk via conda, but failed.
It said there is no package, I wander it's because of wrong environment, or other issues.
Any help will be appreciated.

Best, Kun

Below is the code:

[login1 ~] $ which python2
~/anaconda2/bin/python2
[login1 ~]$ which conda
~/anaconda2/bin/conda
[login1 ~]$ conda install slamdunk
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - slamdunk

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by t-neumann** [comment]
Did you setup bioconda?

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by kunUCSD** [comment]
Thank you, Neumann,

It worked for me.

Best, Kun
