### ISSUE TITLE
when installing slamdunk using conda, not finding NextGenMap

### ISSUE THREAD

**Issue by RippeiHayashi** [t-neumann/slamdunk#45]
Hi Tobias,

I want to install slamdunk on the cluster (Linux 3.10.0-862.14.4.el6.x86_64) where I only have the write permission to my user home directory.

I chose to use Anaconda2 to install slamdunk.
In that case, where am I supposed to install NextGenMap?

In your git slamdunk directory, one can find nextgenmap directory where you recommend to install NextGenMap.
But, I don't seem to be able to find NextGenMap directory within 'anaconda2/envs/slamdunk_conda'.
I installed NextGenMap elsewhere instead and added the location to $PATH, but this did not work.

I would appreciate your help.
Best,
Rippei

**Comment by t-neumann** [comment]
Hi @RippeiHayashi 

how did you install slamdunk - did you follow our manual?

```
conda create --name myenv -c bioconda slamdunk
```

This should take care of everything, no need to install NextGenMap separately.

**Comment by t-neumann** [comment]
Does the ngm executable exist in 

```
~/.conda/envs/slamdunk/lib/python2.7/site-packages/slamdunk/contrib/ngm
```

?

**Comment by RippeiHayashi** [comment]
Yes, it does.

**Comment by t-neumann** [comment]
What if you do this before sourcing your env?

```
export PYTHONNOUSERSITE=1
```

**Comment by RippeiHayashi** [comment]
It started mapping meaning that slamdunk successfully found NextGenMap (although the run was killed because of the excessive memory requirement).
Thanks for your help!
Rippei

**Comment by RippeiHayashi** [comment]
Hello Tobias,

sorry to bother you again.
'slamdunk map' didn't seem to invoke samtools.
It successfully finished the mapping and created the sam file, but then the following error came:
---
/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/contrib/samtools: err
or while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
---

Is this related to the same problem as above?

Or is it because the software cannot find the right version of libcrypto.so, perhaps so.1.1 rather than so.1.0.0?
find /anaconda2/envs/slamdunk_conda/lib/ -name 'libcry*'
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/libcrypto.a
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/libcrypto.so
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/libcrypto.so.1.1
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/pkgconfig/libcrypto.pc

Rippei

**Comment by t-neumann** [comment]
Hm this is weird - I have never seen this error to be honest.

Maybe as a quicker workaround - do you have Singularity available on your cluster?

**Comment by RippeiHayashi** [comment]
not quite
I found this QA session.
https://github.com/bioconda/bioconda-recipes/issues/12100
Is this relevant?

**Comment by t-neumann** [comment]
Sounds relevant - did you change the channel order as they suggested?

```
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by RippeiHayashi** [comment]
Yes, I changed the order of channels for conda, reinstalled slamdunk, reran slamdunk map.
This time, samtools worked and it created the bam file.
I will move on to the next step.

Actually, when I first installed slamdunk through conda, I needed to append conda-forge to the channel list.
So my channel order was changed to 
- defaults
- conda-forge
Maybe that's when this problem occurred.

Thanks,
Rippei

**Comment by RippeiHayashi** [comment]
Hi Tobias,

I got the following error when I ran slamdunk count.

Here are the commands that I ran:
---
slamdunk map -r /short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta -o ${tmp1}/slamdunk/${lib} \
-5 0 -n 1 -t 4 ${tmp1}/RNAseq/${lib}/${lib}_STAR_unique_reads_all.fasta

slamdunk filter -o ${tmp1}/slamdunk/${lib} -b ${tmp1}/slamdunk/pachytene_RNAseq_mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed \
-mq 10 -nm 3 -t 4 ${tmp1}/slamdunk/${lib}/${lib}_STAR_unique_reads_all_slamdunk_mapped.bam

slamdunk snp -o ${tmp1}/slamdunk/${lib} -r /short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta \
-c 10 -f 0.001 -t 4 ${tmp1}/slamdunk/${lib}/${lib}_STAR_unique_reads_all_slamdunk_mapped_filtered.bam

slamdunk count -l 150 -o ${tmp1}/slamdunk/${lib} -s ${tmp1}/slamdunk/${lib} -r /short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta \
-b ${tmp1}/slamdunk/pachytene_RNAseq_mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed -t 4 ${tmp1}/slamdunk/${lib}/${lib}_STAR_unique_reads_all_slamdunk_mapped_filtered.bam
---

It successfully generated _filtered_snp.vcf file.
But, it created _filtered_tcount.csv and _filtered_tcount.log files of 0 size, but not bed files.
And here is the error I got:

---
Running slamDunk tcount for 1 files (4 threads)
Traceback (most recent call last):
  File "/short/lf10/software/anaconda2/envs/slamdunk_conda/bin/slamdunk", line 11, in <module>
    sys.exit(run())
  File "/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 474, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory) for tid in range(0, len(args.bam)))
  File "/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/joblib/parallel.py", line 862, in retrieve
    raise exception.unwrap(this_report)
joblib.my_exceptions.JoblibTypeError: JoblibTypeError
___________________________________________________________________________
...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/bin/slamdunk in <module>()
      6 
      7 from slamdunk.slamdunk import run
      8 
      9 if __name__ == '__main__':
     10     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
---> 11     sys.exit(run())

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/slamdunk.py in run()
    469         outputDirectory = args.outputDir
    470         createDir(outputDirectory)
    471         snpDirectory = args.snpDir
    472         n = args.threads
    473         message("Running slamDunk tcount for " + str(len(args.bam)) + " files (" + str(n) + " threads)")
--> 474         results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory) for tid in range(0, len(args.bam)))
        results = undefined
        tid = undefined
    475         dunkFinished()    
    476         
    477     elif (command == "all") :
    478         runAll(args)

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=4), iterable=<generator object <genexpr>>)
    929                 # No need to wait for async callbacks to trigger to
    930                 # consumption.
    931                 self._iterating = False
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=4)>
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time
    937             self._print('Done %3i out of %3i | elapsed: %s finished',
    938                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Joblib worker traceback:
---------------------------------------------------------------------------
TypeError                                          Sat Jan 12 18:11:41 2019
PID: 6780Python 2.7.15: /short/lf10/software/anaconda2/envs/slamdunk_conda/bin/python
...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    220     def __call__(self):
    221         # Set the default nested backend to self._backend but do not set the
    222         # change the default number of processes to -1
    223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
    224             return [func(*args, **kwargs)
--> 225                     for func, args, kwargs in self.items]
        func = <function runCount>
        args = (0, '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...TAR_unique_reads_all_slamdunk_mapped_filtered.bam', '/short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta', '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/pa..._mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed', 150, 27, 1, '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min', '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min')
        kwargs = {}
        self.items = [(<function runCount>, (0, '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...TAR_unique_reads_all_slamdunk_mapped_filtered.bam', '/short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta', '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/pa..._mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed', 150, 27, 1, '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min', '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min'), {})]
    226 
    227     def __len__(self):
    228         return self._size
    229 

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/slamdunk.py in runCount(tid=0, bam='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...TAR_unique_reads_all_slamdunk_mapped_filtered.bam', ref='/short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta', bed='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/pa..._mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed', maxLength=150, minQual=27, conversionThreshold=1, outputDirectory='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min', snpDirectory='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mouse-pachytene-30min')
    193     
    194     log = getLogFile(outputLOG)
    195     
    196     print("Using " + str(maxLength) + " as maximum read length.",file=log)
    197     
--> 198     tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
        ref = '/short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta'
        bed = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/pa..._mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed'
        inputSNP = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...unique_reads_all_slamdunk_mapped_filtered_snp.vcf'
        bam = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...TAR_unique_reads_all_slamdunk_mapped_filtered.bam'
        maxLength = 150
        minQual = 27
        outputCSV = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...que_reads_all_slamdunk_mapped_filtered_tcount.tsv'
        outputBedgraphPlus = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...all_slamdunk_mapped_filtered_tcount_plus.bedgraph'
        outputBedgraphMinus = '/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...all_slamdunk_mapped_filtered_tcount_mins.bedgraph'
        conversionThreshold = 1
        log = <open file '/short/lf10/rh1772/mouse_piRNAs_data...l_slamdunk_mapped_filtered_tcount.log', mode 'a'>
    199     stepFinished()
    200     return outputCSV
    201             
    202 def runAll(args) :

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/dunks/tcounter.py in computeTconversions(ref='/short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta', bed='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/pa..._mm10_tiles_no-rRNA-miscRNAs_gt-10RPKM_merged.bed', snpsFile='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...unique_reads_all_slamdunk_mapped_filtered_snp.vcf', bam='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...TAR_unique_reads_all_slamdunk_mapped_filtered.bam', maxReadLength=150, minQual=27, outputCSV='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...que_reads_all_slamdunk_mapped_filtered_tcount.tsv', outputBedgraphPlus='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...all_slamdunk_mapped_filtered_tcount_plus.bedgraph', outputBedgraphMinus='/short/lf10/rh1772/mouse_piRNAs_data/slamdunk/mo...all_slamdunk_mapped_filtered_tcount_mins.bedgraph', conversionThreshold=1, log=<open file '/short/lf10/rh1772/mouse_piRNAs_data...l_slamdunk_mapped_filtered_tcount.log', mode 'a'>, mle=False)
    202         tCountRev = 0
    203         
    204         multiMapFwd = 0
    205         multiMapRev = 0
    206         
--> 207         for read in readIterator:
        read = undefined
        readIterator = <slamdunk.slamseq.SlamSeqFile.SlamSeqBamIterator instance>
    208             
    209             # Overwrite any conversions for non-TC reads (reads with < 2 TC conversions)
    210             if (not read.isTcRead) :
    211                 read.tcCount = 0

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/slamseq/SlamSeqFile.py in next(self=<slamdunk.slamseq.SlamSeqFile.SlamSeqBamIterator instance>)
    378         if (read.mapping_quality == 0) :
    379             slamSeqRead.isMultimapper = True
    380         else :
    381             slamSeqRead.isMultimapper = False
    382 
--> 383         slamSeqRead.mismatches, slamSeqRead.tcCount = self.fillMismatchesNGM(read)
        slamSeqRead.mismatches = []
        slamSeqRead.tcCount = None
        self.fillMismatchesNGM = <bound method SlamSeqBamIterator.fillMismatchesN...slamseq.SlamSeqFile.SlamSeqBamIterator instance>>
        read = <pysam.libcalignedsegment.AlignedSegment object>
    384         slamSeqRead.conversionRates = self.computeRatesForRead(read, slamSeqRead.mismatches)
    385         slamSeqRead.startRefPos = read.reference_start - int(self._startPosition)
    386         slamSeqRead.endRefPos = read.reference_end - int(self._startPosition)
    387 

...........................................................................
/short/lf10/software/anaconda2/envs/slamdunk_conda/lib/python2.7/site-packages/slamdunk/slamseq/SlamSeqFile.py in fillMismatchesNGM(self=<slamdunk.slamseq.SlamSeqFile.SlamSeqBamIterator instance>, read=<pysam.libcalignedsegment.AlignedSegment object>)
    321             for mismatch in ngmMismatches:
    322                 conversion, readPos, refPos = mismatch.split(":")
    323                 refBase, readBase = self.MPTagToConversion(conversion)
    324                 readPos = int(readPos) - 1
    325 
--> 326                 readQlty = read.query_qualities[readPos]
        readQlty = undefined
        read.query_qualities = None
        readPos = 5
    327                 if readQlty >= self._minQual:
    328                     refPos = int(refPos) - 1
    329 
    330                     if(read.is_reverse):

TypeError: 'NoneType' object has no attribute '__getitem__'
___________________________________________________________________________


$ pip freeze | grep joblib
joblib==0.13.1
$ slamdunk --version
slamdunk 0.3.3

Could you help?
Rippei

**Comment by t-neumann** [comment]
Hi Rippei, sorry for getting back so late.

For this, is there a way you could send me one of the filtered bam + corresponding vcf files along with the bed file and genome.fa you use? Hard to tell what's going on from here.

**Comment by RippeiHayashi** [comment]
Thanks Tobias for helping me with this.
Here is the link.
https://cloudstor.aarnet.edu.au/sender/?s=download&token=d7f9d069-2236-d0c4-ae30-0ea41d3e709a

**Comment by RippeiHayashi** [comment]
No worries Tobias,
I wonder if the list of "UTRs" was not appropriate. I did not use the collection of 3'UTRs as I did a conventional RNA seq instead of Quant Seq.
I may try the published data from Herzog, et al. and use 3'UTRs.
Rippei

**Comment by t-neumann** [comment]
Hi Rippei,

I can reproduce the error and I will look into it. If you did conventional RNAseq you would lose a lot of signal by sticking to 3' UTRs, this should be fine. The assay was stranded from what I can see, so this should also be fine.

However the bam file looks ver, very weird. How to the fastq-files look on which you ran this? They do not contain any base quality scores (which causes the error above, and then there's also some very weird lines where the read sequence seems to start after the read ID?

```
E00491:325:HVM7FCCXY:6:2210:26463:50709 16      chr1    3222003 60      137M    *       0       0       ACTTGGGATTGAATGCTTTAAAAATAAATGATTCTATTAGTGAAGTAAGTTTAACTGTTGTACATTCCTGACCTCAAAATTGCTCTTAAACTTAAAATTTTTTTAAAAAGTAATTTACTAAAAATCTGTCAGATGGT       *       RG:Z:0  AS:i:1370       NM:i:0  NH:i:1  XI:f:1  X0:i:1  XA:i:0  XE:i:39 XR:i:137        MD:Z:137        TC:i:0  RA:Z:50,0,0,0,0,0,16,0,0,0,0,0,19,0,0,0,0,0,52,0,0,0,0,0,0
E00491:325:HVM7FCCXY:6:1104:12723:24198@GTGCTGAGAAGAAGGTATAGTCTTTTGTTTTAGGATAAAATGTTCTGTAGATATCTGTT     16      chr1    3232016 7       98M     *       0       0       CACAGTGAAACTAACAGAAGTGATGAAACAAATGGACTTAACAGATATCTACAGAACATTTTATCCTAAAACAAAAGACTATACCTTCTTCTCAGCAC      *       RG:Z:0  AS:i:905        NM:i:3  NH:i:1  XI:f:0.9694     X0:i:1  XA:i:0  XE:i:5  XR:i:98 MD:Z:21T14TC60  TC:i:0  RA:Z:42,0,0,0,0,0,20,0,1,0,0,0,11,0,0,0,1,1,22,0,0,0,0,0,0      MP:Z:17:22:22,16:37:37,8:38:38
E00491:325:HVM7FCCXY:6:2221:25550:65687@CTCATGGTTACCTTCTCCAAAACTGACCACATAATTGGTCACAAAACAAGCCTCAACAG     0       chr1    3232114 6       145M    *       0       0       CTCATGGTTACCTTCTCCAAAACTGACCACATAATTGGTCACAAAACAAGCCTCAACAGATACAAAAATATTGAAATTGTCCCATGTATCCTATCAGATTACCATGGACTAAGGCTGATCTTCAATAACAAAATAAATAATAGAA       *       RG:Z:0  AS:i:1450       NM:i:0  NH:i:1  XI:f:1  X0:i:1  XA:i:0  XE:i:13 XR:i:145        MD:Z:145        TC:i:0  RA:Z:59,0,0,0,0,0,32,0,0,0,0,0,17,0,0,0,0,0,37,0,0,0,0,0,0
E00491:325:HVM7FCCXY:6:2221:17990:71154 16      chr1    3328102 60      130M    *       0       0       CTGAGACAGAAGGAAGGACCATCCAGAGACTGCCCCAACTGGGGATCCATCTCATAAACAGCCACTAAACCCAGACAGTATTGCATATGCCAGAAAGATTTTGCTGACAGGACCCCAATTTAGCTGTCTC      *       RG:Z:0  AS:i:1300       NM:i:0  NH:i:1  XI:f:1  X0:i:1  XA:i:0  XE:i:31 XR:i:130        MD:Z:130        TC:i:0  RA:Z:42,0,0,0,0,0,36,0,0,0,0,0,27,0,0,0,0,0,25,0,0,0,0,0,0
```

Just as a reference, this is how the bam files look usually when you run NGM on them:

```
7001253F:611:CCRE8ANXX:5:2213:18728:54574#TTCCGC        16      chr10   114343  60      88M     *       0       0       AGTCTTTTTCTGTCGCCCGGGCTGGAGTGTAGTGGCACGATCTCAGCTCACTGCAAACTCCGCCTCCAGGGTTCAAGTAATTCTCCTG        7//FFFFBFFFFBBB/BFFFF</F7/FB</FB<FF<</F<</BFBFFFFF<FFF</7</////FFFBFFFBFF/FFFFFFFFBB//<F        AS:i:855        NM:i:1  NH:i:1  XI:f:0.9886     XA:i:0  X0:i:1  XE:i:8  XR:i:88 MD:Z:29C58      RG:Z:0  TC:i:0  RA:Z:15,0,0,0,0,0,26,0,1,0,0,0,22,0,0,0,0,0,24,0,0,0,0,0,0,     MP:Z:8:30:30
7001253F:611:CCRE8ANXX:5:1301:3537:72590#TTCCGC 16      chr10   127395  60      88M     *       0       0       ATTTTTTCATAACACTTTGTGGTCTCTTTCTACTAATATACATGTTTATTTTTACACTATATGATCCTTTTCTTTAACGTCTATCCTA
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        AS:i:880        NM:i:0  NH:i:1  XI:f:1  XA:i:0  X0:i:1  XE:i:25 XR:i:88 MD:Z:88 RG:Z:0  TC:i:0  RA:Z:21,0,0,0,0,0,17,0,0,0,0,0,6,0,0,0,0,0,44,0,0,0,0,0,0,
7001253F:611:CCRE8ANXX:5:1309:16969:4976#TTCCGC 16      chr10   131691  60      5S75M   *       0       0       CAATTTTTTTTTTTTTTTTTTTTGTAGAGATGCGTCCTCGTTATGTTGCCCAGGCTGTTCTCGAACTCCTGGCCCCAAGT        <<//FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        AS:i:700        NM:i:2  NH:i:1  XI:f:0.9733     XA:i:0  X0:i:1  XE:i:10 XR:i:75 MD:Z:12AA61     RG:Z:0  TC:i:0  RA:Z:9,0,0,2,0,0,17,0,0,0,0,0,15,0,0,0,0,0,32,0,0,0,0,0,0,      MP:Z:3:18:13,3:19:14
```

**Comment by RippeiHayashi** [comment]
Hi Tobias,
Sorry to confuse you with the bam file I sent.
It was produced through slamdunk using a fasta file as an input:

slamdunk map -r /short/lf10/rh1772/mouse_piRNAs_old/indices/mm10/mm10.fasta -o ${tmp1}/slamdunk/${lib} 
-5 0 -n 1 -t 4 ${tmp1}/RNAseq/${lib}/${lib}_STAR_unique_reads_all.fasta

Does slamdunk not support fasta files, which do not have the quality scores?

I ran STAR mapping to first exclude any genome multi mappers before feeding reads into slamdunk.
That's where I lost quality scores.
Maybe this was not necessary at all.
The sequence after @ was indeed the original reads. I added this for some sanity check. Would it affect anything?

Rippei

**Comment by t-neumann** [comment]
Ah ok I see, well nobody ever tested it with fasta files since I can hardly think of scenarios where they would not be available, but NextGenMap apparently still handles them.

Slamdunk automatically excludes multimappers if you run it with the default settings. Any multimapper would have a mapping quality of 0 and thus be excluded by the filtering step.

Regarding the read sequence after the @ I think that is fine, it just added another level of confusion. But we definitely need the quality scores.

**Comment by RippeiHayashi** [comment]
Thanks, Tobias,
Perhaps I did not read the instruction carefully enough.
I vaguely recalled back in Vienna that some inverted duplicated mappers cause a problem.

Besides, SlamDunk Documentation does seem to allow fasta files as input for slamdunk map function.

File | Description
-- | --
Reference fasta | The reference sequence of the genome to map against in fasta format.
files | Samplesheet (see Sample file format ) or a list of all sample BAM/FASTA(gz)/FASTQ(gz) files (wildcard * accepted).

But, I will simply redo the analysis using original fastq files.
Will let you know how it goes.

Rippei

**Comment by t-neumann** [comment]
Oops sorry then the documentation is wrong on that. Thanks for pointing this out to us.
We did not have any base-quality checks included in earlier SlamDunk versions, but at some point we did and probably we forgot to fix this in the docs.

Yes please try it with the original fastq files and let me know if you encounter any more issues.

Sorry again

Tobi

**Comment by RippeiHayashi** [comment]
It worked when I used fastq files as input.
Thanks a lot for your help!!
Rippei
