### ISSUE TITLE
error running slamdunk all 

### ISSUE THREAD

**Issue by dmiyagi** [t-neumann/slamdunk#46]
I am trying to run slamdunk all using UCSC 38 genome and corresponding 3utr.bed file with my samples formatted as specified in a text named sampleInfo.tsv as shown: 
`$ slamdunk all -r genome.fa -b 3utr.bed  -o ~/slamseq/ -5 12 -n 100 -m sampleInfo.tsv`
and am receiving this error: 
`slamdunk all
Running slamDunk map for 1 files (1 threads)
Traceback (most recent call last):
  File "/home/dfm42/project/tools/slamdunk/bin/slamdunk", line 28, in <module>
    slamdunk.run()
  File "/home/dfm42/project/tools/slamdunk/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/home/dfm42/project/tools/slamdunk/slamdunk/slamdunk.py", line 233, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/home/dfm42/project/tools/slamdunk/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/home/dfm42/project/tools/slamdunk/slamdunk/dunks/mapper.py", line 104, in Map
    run(getBinary("ngm") + " -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/home/dfm42/project/tools/slamdunk/slamdunk/utils/misc.py", line 190, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: slamdunk all -r genome.fa -b 3utr.bed  -o ~/slamseq/ -5 12 -n 100 -m file.fastq.gz`

**Comment by t-neumann** [comment]
Could you look into the *log files in the map subfolder what is written there?

**Comment by dmiyagi** [comment]
```
~/slamdunk/contrib/ngm: line 16:~/slamdunk/contrib/ngm-core: No such file or directory
~/slamdunk/contrib/ngm: line 16:~/slamdunk/contrib/ngm-core: No such file or directory
```

so I looked in the slamdunk/contrib/ folder and tried to run ./build-ngm.sh again and realize that it may have never installed because I get a very, very long error (pages) with the end of it saying
`make[2]: *** [../bin/ngm-0.5.2/ngm-core-debug] Error 1
make[1]: *** [src/CMakeFiles/ngm-core-debug.dir/all] Error 2
make: *** [all] Error 2`

**Comment by t-neumann** [comment]
Hi,

ok I should get rid of the manual installation instructions. These days, actually only installation via ```bioconda```, ```pip``` or simply utilizing the Docker image is recommended.

Could you try on of these options?

**Comment by dmiyagi** [comment]
Ok I used bioconda and it now works for a few seconds before giving me the same error `slamdunk all
Running slamDunk map for 17 files (1 threads)
Traceback (most recent call last):
  File "/home/dfm42/project/conda_envs/slamdunk/bin/slamdunk", line 11, in <module>
    sys.exit(run())
  File "/home/dfm42/project/conda_envs/slamdunk/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/home/dfm42/project/conda_envs/slamdunk/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 233, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/home/dfm42/project/conda_envs/slamdunk/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/home/dfm42/project/conda_envs/slamdunk/lib/python2.7/site-packages/slamdunk/dunks/mapper.py", line 104, in Map
    run(getBinary("ngm") + " -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/home/dfm42/project/conda_envs/slamdunk/lib/python2.7/site-packages/slamdunk/utils/misc.py", line 190, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "~/slamdunk/contrib/ngm -r ~/genome.fa -q ~ file.fastq.gz -t 1 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l  --rg-id 0 --rg-sm gfp-tp6-2:gfp-tp6-2:360 -n 100 --strata  -o ~.fastq_slamdunk_mapped.sam"` and then in the map log it says `[MAIN] NextGenMap 0.5.2
[MAIN] Startup : x64 (build Feb 13 2019 14:54:40)
[MAIN] Starting time: 2019-02-18.19:07:57
[CONFIG] Parameter:  --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 1 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --f$
[NGM] Opening for output (SAM):~file.sam
[SEQPROV] Encoding reference sequence.
[SEQPROV] Size of reference genome 3100 Mbp (max. 17179 Mbp)
[SEQPROV] Allocating 1550059416 (3161924569) bytes for the reference.
[SEQPROV] BinRef length: 1550059321ll (elapsed 12.877669)
[SEQPROV] 0 reference sequences were skipped (length < 10).
[SEQPROV] Writing encoded reference to /gpfs/ycga/datasets/genomes/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa-enc.2.ngm

`

**Comment by dmiyagi** [comment]
UPDATE: I believe I've solved the issue by making my sequence folder local as this was trying to write to a folder which I do not have write permissions in. Seems to be working fine now. Thank you so much for your help!

**Comment by t-neumann** [comment]
Perfect - that is what I would have also suspected.
