### ISSUE TITLE
conversion in CDS

### ISSUE THREAD

**Issue by CSdady** [t-neumann/slamdunk#47]
Is it possible to calculate conversion rate in protein coding regions instead of 3-UTRs?

**Comment by t-neumann** [comment]
You can supply any genomic interval you want as bed file. Of course the quantifications only make sense if you also expect signal in those intervals - for QuantSeq, these are naturally 3' ends of transcripts.

**Comment by CSdady** [comment]
Thank you for a quick response.
Thus, when I can supply bedfiles for specific genomic intervals such as CDS, 5'-UTR, or others, I can extract data as far as library prep and sequencing can cover (e.g. whole transcript sequencing). right?

**Comment by t-neumann** [comment]
Yes you are correct. Good luck!
