### ISSUE TITLE
Query about running the slamdunk all

### ISSUE THREAD

**Issue by kunUCSD** [t-neumann/slamdunk#48]
Hi Neumann,
Recently, I updated to the slamdunk 0.3.4 and tried to run the "slamdunk all" but only got the map and filter data. In the V0.3.3, my code worked well. Below is my code:
slamdunk all -r genome.fa -b mm10_3UTR.bed -o output -5 12 -t 8 -m --skip-sam ./mergedfastq/KT117_1_S1_R1_001.fastq.gz
Another issue is that when I run with nodes=1:ppn=8, it will finish ~25hrs (I have 14 samples in total), but when I give nodes=1:ppn=16, it will spend ~45hrs. Do you know why?
Best, 
Kun

**Comment by t-neumann** [comment]
Can you give me an error? Do you have the vcf files in the snp subdir produced? What exactly is not working?

Did you specify your nodes only for your job submission or did you also specify the thread number with  `-t`?

**Comment by kunUCSD** [comment]
Hi Neumann,
There are only map and filter subdir produced after running the slamdunk all. The filter subdir shows bam and bam_tmp files, not the bai files. I think that's why?
The slamdunk.log showed "RuntimeError: Error while executing command:" 

I specified the job nodes, and also the thread number (-t 8), as you can tell from my code: 
slamdunk all -r genome.fa -b mm10_3UTR.bed -o output -5 12 -t 8 -m --skip-sam ./*.fastq.gz. 

Best, Kun

**Comment by t-neumann** [comment]
Can you send me the input of one of the `.log` files in the `map` subfolder, as well as one in the `filter` subfolder?

Sorry yes - I missed that. Just as a blind test - what happens if you use the same `-t` number in both runs?

**Comment by kunUCSD** [comment]
Hi Neumann,
Please find the attachment. The filter log file seems empty.
I tried the same -t 8, and the higher job nodes (16) will spend more time, it's weird.
Best, Kun

________________________________

**Comment by kunUCSD** [comment]
Hi Neumann,
You may also need to check this file? It's the running error from slamdunkall.
[Slamdunk_err.log](https://github.com/t-neumann/slamdunk/files/2963720/Slamdunk_err.log)
Best, Kun

**Comment by kunUCSD** [comment]
Hi Neumann,
I tried to run the slamdunk filter only, and found the error. Please check the attachment. Could you help to figure it out? Thanks.
[filter_err.log](https://github.com/t-neumann/slamdunk/files/2968180/filter_err.log)
My filter code is: slamdunk filter -o out_T/filter -b mm10_3UTR.bed -t 7 out_T/map/KT117_1_S1_R1_001.fastq_slamdunk_mapped.bam
Best, Kun

**Comment by t-neumann** [comment]
Hi Kun,

can you just as sanity check try to run it single-threaded with `-t 1`?

**Comment by kunUCSD** [comment]
Hi Neumann,

I run the -t 1, and the filter error is:
./anaconda2/lib/python2.7/site-packages/slamdunk/contrib/samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Something wrong with my installation? I just followed the same way for the installation. After installation, I run the slamdunk -h, and it worked well...

Best, Kun


> Hi Kun,
> 
> can you just as sanity check try to run it single-threaded with `-t 1`?

**Comment by t-neumann** [comment]
Can you try to recreate your slamdunk conda env?

Looks like they fixed a major samtools issue recently: https://github.com/bioconda/bioconda-recipes/issues/13958

**Comment by t-neumann** [comment]
Did recreating a fresh conda environment help?

**Comment by kunUCSD** [comment]
Hi Neumann,

Sorry for the delayed reply, but our server’s going slow now, the job is still in line. Will let you know once I get the result.
Best,
Kun

On Mar 21, 2019, at 7:23 AM, Tobias Neumann <notifications@github.com<mailto:notifications@github.com>> wrote:


Did recreating a fresh conda environment help?

**Comment by kunUCSD** [comment]
Hi Neumann, 
After downgrade the OpenSSL version, not upgrade the samtools, the same cade works well. I guess it's because slamdunk call the old version of OpenSSL.
Thanks for all your helps!
Cheers,
Kun
