### ISSUE TITLE
SNP calling is skipped

### ISSUE THREAD

**Issue by bdespard** [t-neumann/slamdunk#49]
When running slamdunk snp, SNP calling is reported "skipped" in the log files (see bold).

When PCR duplicates are removed using UMI, SNP calling is not skipped. 

In both cases, slamdunk snp still outputs a vcf file containing SNP positions.

Output of the log file:

Only SNPs will be reported
Warning: No p-value threshold provided, so p-values will not be calculated
Min coverage:   2
[mpileup] 1 samples in 1 input files
Min reads2:     2
Min var freq:   0.8
Min avg qual:   15
P-value thresh: 0.01
Input stream not ready, waiting for 5 seconds...
Reading input from STDIN
76780862 bases in pileup file
35501 variant positions (32869 SNP, 2632 indel)
0 were failed by the strand-filter
32869 variant positions reported (32869 SNP, 0 indel)
**Skipping SNP calling**
HepG2_short_DMSO_rep1.processed.fastq_slamdunk_mapped_filtered_snp.log (END)

**Comment by t-neumann** [comment]
Hi @bdespard 
Hm so you get actually vcf files with content right?
Might be this is some wrong logging info. I will have a look and get back to you by the end of the week.

**Comment by bdespard** [comment]
Yes, the vcf files have content but since encountering this issue I'm
unable to replicate the skipping result even using the same input files. So
maybe it was a one-time crash or something. Not sure.

V/R
Brendan

**Comment by t-neumann** [comment]
Hm - ok maybe that was what's going on. I'll close it for now, but please get back to me again on this issue if this keeps happening.
