### ISSUE TITLE
y axis in utrrates graph

### ISSUE THREAD

**Issue by CSdady** [t-neumann/slamdunk#50]
HI Tobias,

I find the range of y axis value changes automatically depending on the range of value, when I run "alleyoop utrrates" command.
Could you let me know how I can change y axis values manually?

Thank you.

**Comment by t-neumann** [comment]
Hi,

yes that is how it is currently implemented and I have yet to add a parameter to set this range manually.

However, for the MultiQC report you can create for all samples in a run, you will have a common scale for all - would this help as a workaround in the meanwhile?

Cheers

**Comment by CSdady** [comment]
Thank you for a quick answer.
I have tried multiqc to create utrrate comparison however it showed this warning message "  multiqc : No analysis results found. Cleaning up.."  and didn't generate report.
Since multiqc worked well for overrallrates comparison, I don't think there was a problem during installation.
Could you let me know if you have any idea how to fix this problem?

**Comment by t-neumann** [comment]
Hm can you look at the `mutationrates_utr.csv` files and check if there is some actual content inside?
