### ISSUE TITLE
Question about Downstream Analysis

### ISSUE THREAD

**Issue by dmiyagi** [t-neumann/slamdunk#52]
For our experiments, we used Lexogen catabolic Slamseq kit and we were able to analyze our data by using your Slamdunk software. It's clear that T>C conversion was dramatically higher than other base conversions and corresponding samples are clustering well too, so our experiments are definitely working. But we have some questions in regards to how to proceed with the downstream analysis for measuring the transcript half-life. I was wondering if you could kindly help us with some of our questions. 

1)      To my understanding, it would be appropriate if we use T>C conversion rate only to fit the data to an exponential one phase decay and calculate RNA half-life accordingly. Our experiment is a pulse-chase experiment and we have 18 samples with three-time points (TP0, TP3, and TP6) with three biological replicates of two conditions (Overexpression and Control). I would like to know if we also need a background sample to subtract TC read number or would that be possible if we only exclude the transcripts with less than 2 TC conversion as mentioned in the Science paper. If we can set the threshold to > 2TC conversion, which column ( in Slamdunk output) should we apply this threshold?  Is this the "ConversionsOnTs" or"TcReadCount"?

2)      My other question is about the TC conversion rates. Given the nature of our experiment, I am expecting to see the TC conversion rates are highest at time point 0 and should go down in time point 3 and time point 6. In a few transcripts though, I can see that TC conversion rates are higher in TP3 and 6 compared to TP0. There are few transcripts in our control samples which have this pattern but the number of transcripts is higher in our "overexpression" group.  How can we explain that? Should we exclude them or is this something that is also observed in your experiments? 

3)      And my last question, Is there a need to set any threshold for multi-mapping reads using "multimapCount" column in Slamdunk output?

I greatly appreciate your time and your interest in advance.

**Comment by t-neumann** [comment]
Hi @dmiyagi - sorry I must have overlooked this issue, thus the late reply.

1. I never got to the point of estimating half-lifes, this was done by my collaborators. I am pretty sure though, that they used 1 T>C conversion as their threshold to get to the TC-reads number and had a control sample to subtract as background. If you set the threshold to > 2 TC conversions, you do this already when you set the parameter in slamdunk - the TCReadCount column will then already only contain those reads passing this threshold.

2. Hm did you look at absolute read numbers for these transcripts? Are they so low that the changes conversion rates can be merely stochastic?

3. No, this was basically our way of getting to transcripts with a lot of multimapping reads and checking properties of those. We never did any filtering on this number.
