### ISSUE TITLE
Problem with final count

### ISSUE THREAD

**Issue by moodswh** [t-neumann/slamdunk#54]
Hi Tobias,
Recently, I'm try to analysis my SLAM-seq data (mouse) by SLAMDUNK (installed by conda 4.7.10) and follow the protocol from SLAM-ITseq: Nature Protocols 14, pages 2261–2278 (2019).

Here is my code:
`slamdunk all -r Mus_musculus.GRCm38.dna.primary_assembly.fa -b tb_wgEncodeGencodeBasicVM22.bed -t 5 -5 12 *.gz -o Slamdunk`

But it can't generate the count matrix, only four files here:

_237      slam.fastq_slamdunk_mapped_filtered_tcount.log
 0         slam.fastq_slamdunk_mapped_filtered_tcount_mins.bedgraph
 0         slam.fastq_slamdunk_mapped_filtered_tcount_plus.bedgraph
6.9M    slam.fastq_slamdunk_mapped_filtered_tcount.tsv_

The .log file show:
`Using 74 as maximum read length.
Warning: MD5 checksum of annotation (532bbf52495f2c592ce60242a876fb81) does not matched MD5 in filtered BAM files (). Most probably the annotation filed changed after the filtered BAM files were created.`

And only number “0” in Tcontent CoverageOnTs/ConversionsOnTs/ReadCount...

Thanks a lot!
Hua

**Comment by t-neumann** [comment]
Hi @moodswh 

I have some suspicion: Can you `grep` for the chromosome names in your reference fasta like this?

`grep ">" Mus_musculus.GRCm38.dna.primary_assembly.fa | head`

and then please `head` the first couple of lines from your annotation

`head tb_wgEncodeGencodeBasicVM22.bed`

Can you paste that in here?

**Comment by moodswh** [comment]
@t-neumann 
Thank you fast reply! Here are the info:


`grep ">" Mus_musculus.GRCm38.dna.primary_assembly.fa | head`

>1 dna:chromosome chromosome:GRCm38:1:1:195471971:1 REF
>10 dna:chromosome chromosome:GRCm38:10:1:130694993:1 REF
>11 dna:chromosome chromosome:GRCm38:11:1:122082543:1 REF
>12 dna:chromosome chromosome:GRCm38:12:1:120129022:1 REF
>13 dna:chromosome chromosome:GRCm38:13:1:120421639:1 REF
>14 dna:chromosome chromosome:GRCm38:14:1:124902244:1 REF
>15 dna:chromosome chromosome:GRCm38:15:1:104043685:1 REF
>16 dna:chromosome chromosome:GRCm38:16:1:98207768:1 REF
>17 dna:chromosome chromosome:GRCm38:17:1:94987271:1 REF
>18 dna:chromosome chromosome:GRCm38:18:1:90702639:1 REF

`head tb_wgEncodeGencodeBasicVM22.bed`

chr1	134199222	134201713	ENSMUST00000169927.1_utr3_0_0_chr1_134199223_r	0	-
chr1	134202064	134202950	ENSMUST00000169927.1_utr3_1_0_chr1_134202065_r	0	-
chr1	134199224	134202950	ENSMUST00000086465.5_utr3_0_0_chr1_134199225_r	0	-
chr1	134201348	134202950	ENSMUST00000038191.7_utr3_0_0_chr1_134201349_r	0	-
chr1	8361474	8363474	ENSMUST00000132064.7_utr3_0_0_chr1_8361475_r	0	-
chr1	8361474	8363474	ENSMUST00000191683.5_utr3_0_0_chr1_8361475_r	0	-
chr1	8361474	8363474	ENSMUST00000140295.7_utr3_0_0_chr1_8361475_r	0	-
chr1	25067475	25068167	ENSMUST00000126626.7_utr3_0_0_chr1_25067476_r	0	-
chr1	25067549	25068167	ENSMUST00000135518.7_utr3_0_0_chr1_25067550_r	0	-
chr1	25067549	25068167	ENSMUST00000151309.7_utr3_0_0_chr1_25067550_r	0	-

Thank you

**Comment by t-neumann** [comment]
I see - try this into a new bed file and run it with this:

`sed -e 's/^chr//g' tb_wgEncodeGencodeBasicVM22.bed`

I think the problem is the mismatch of chromosome names in reference and bed file. I recommend to always use `mm10` from UCSC.

**Comment by moodswh** [comment]
@t-neumann 
Hi Tobias,
Yes, now it's work well, I didn't realize it before. Thank you a million.
