### ISSUE TITLE
error in SLAMdunk: ".local/lib/python2.7/site-packages/slamdunk/contrib/ngm: No such file or directory"

### ISSUE THREAD

**Issue by amitblum** [t-neumann/slamdunk#55]
Hello
I tried to install SLAMdunk using your recommendation:
conda create --name myenv -c bioconda slamdunk

From some reasons, while runnig SLAMdunk I have error.
The log file message is: 
.local/lib/python2.7/site-packages/slamdunk/contrib/ngm: No such file or directory

ls for this directory, give me the following: 
build-ngm.sh  build-rnaseqreadsimulator.sh  build-samtools.sh  build-varscan.sh  __init__.py  __init__.pyc  nextgenmap

Anything that I should do in order to solve that problem?

Thanks
Amit

**Comment by t-neumann** [comment]
Hm what is in your conda env folder?

Must be something like this:

```~/.conda/envs/myenv/lib/python2.7/site-packages/slamdunk/contrib/ngm```

Does this exist?

If yes, try this before loading the conda env:

```export PYTHONNOUSERSITE=1```

**Comment by amitblum** [comment]
thanks. will try it

**Comment by t-neumann** [comment]
@amitblum can this be closed?
