### ISSUE TITLE
-mts flag

### ISSUE THREAD

**Issue by dmiyagi** [t-neumann/slamdunk#56]
Hi again t-neumann, 

Thanks for answering my previous questions. I am trying to rerun slamdunk all with the -mts flag; however, I keep running into this error: 
```
`usage: slamdunk all [-h] -r REFERENCEFILE -b BED [-fb FILTERBED] -o OUTPUTDIR
                    [-5 TRIM5] [-a MAXPOLYA] [-n TOPN] [-t THREADS] [-q] [-e]
                    [-m] [-mq MQ] [-mi IDENTITY] [-nm NM] [-mc COV] [-mv VAR]
                    [-c CONVERSIONTHRESHOLD] [-rl MAXLENGTH] [-mbq MINQUAL]
                    [-i SAMPLEINDEX] [-ss]
                    files [files ...]
slamdunk all: error: argument -t/--threads: invalid int value: 's'


```
I noticed that in the explanation it doesn't  have `-mts` but rather has `-c CONVERSIONTHRESHOLD ` I thought this might mean that I'm using an older version of slamdunk so I reinstalled/updated it and am still having this issue. It should be noted that I am not using the `-t` parameter in my code. I also tried `--multiTCStringency` and got `usage: slamdunk [-h] [--version] {map,filter,snp,count,all} ...
slamdunk: error: unrecognized arguments: --multiTCStringency`. Any suggestions? is the `-c` flag equivalent to the `-mts` flag if I set it to `-c 2` ? Thanks!

**Comment by dmiyagi** [comment]
It's probably helpful if I leave this here as well `slamdunk all -r /path/to/hg38.fa -b /path/to/3utr.bed  -o /path/to/slamseq/ -m -n 100 --multiTCStringency /path/to/sampleInfo.tsv`

**Comment by t-neumann** [comment]
Hi @dmiyagi 

yes you are correct, the `-c` flag replaces the `-mts` flag in newer versions of Slamdunk. With `-mts` the conversion threshold to call a read as `TCRead` was hard-coded to 2 T>C conversions, with the new `-c` flag you can dynamically define this threshold on your own. So indeed, setting `-c 2` is equivalent to the previous `-mts` flag.
