### ISSUE TITLE
Bed file for the whole transcriptome

### ISSUE THREAD

**Issue by aleighbrown** [t-neumann/slamdunk#58]
I know this software is designed for 3' utrs, but in theory it should work the same if you feed it a bed file for the whole transcriptome correct?

Wondering if you have an recommendations for doing that/if it works fine, etc.

**Comment by t-neumann** [comment]
Hi @aleighbrown 

it would quantify nucleotide-conversions in whatever intervals you feed in with a bed file.

So yes, you could map reads against transcripts and then quantify those (which we have already been experimenting with).

Currently, the HiSat2 Team is integrating our approach into their next release (which will still take a couple of months) - then spliced-alignments will also be possible.

**Comment by aleighbrown** [comment]
Do you have any recommendations for how to make a bed file for transcript? 

I used genecodes GTF + BEDOPS gtf2bed tools to make one, but I got some kind of funky results, which I think it due to the bed file itself being made improperly

See brief example attached, but in essence I was getting a lot of "transcripts" that were like...3 bp long or 47000 long, when the gene itself isn't long

[small_sample.txt](https://github.com/t-neumann/slamdunk/files/3579309/small_sample.txt)

**Comment by t-neumann** [comment]
Honestly, I would just download one of the transcript fasta files from [Gencode](https://www.gencodegenes.org/human/).

With `samtools faidx` you would get the individual lengths which you can easily awk into a bed-file with one entry covering one transcript.

**Comment by aleighbrown** [comment]
Sweet thanks; I'll close issue once I've run it successfully

**Comment by t-neumann** [comment]
@aleighbrown can this be closed?

**Comment by aleighbrown** [comment]
Yep! Sorry about that
