### ISSUE TITLE
alleyoop RuntimeError

### ISSUE THREAD

**Issue by kunUCSD** [t-neumann/slamdunk#59]
Hi there,
When running the alley, I got this error (as shown below). I tried to uninstall and re-install slamdunk, as well as delete all slamdunk R packages, and still got this error. I guess it's the "globalRatePlotter.R" doesn't work well, or the route is wrong? Any suggestions to fix this? Thanks

Kun
 
/home/kun/anaconda2/lib/python2.7/site-packages/slamdunk/utils/misc.py in callR(cmd='/home/kun/anaconda2/lib/python2.7/site-package...tq_slamdunk_mapped_filtered_mutationrates_utr.pdf', log=<open file 'out_T/alleyoop/Kn17_1_S1_L005_R1_001...mapped_filtered_mutationrates_utr.log', mode 'a'>, verbose=True, dry=False)
    207         lines_iterator = iter(p.stdout.readline, b"")
    208         for line in lines_iterator:
    209             print(line, end="", file=log) # yield line
    210         p.wait();
    211         if(p.returncode != 0):
--> 212             raise RuntimeError("Error while executing command: \"" + cmd + "\"")
        cmd = '/home/kun/anaconda2/lib/python2.7/site-package...tq_slamdunk_mapped_filtered_mutationrates_utr.pdf'
    213
    214 def pysamIndex(outputBam):
    215     pysam.index(outputBam)  # @UndefinedVariable
    216

RuntimeError: Error while executing command: "/home/kun/anaconda2/lib/python2.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmp4Tnx7o -O out_T/alleyoop/Kn17_1_S1_L005_R1_001.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf"

**Comment by t-neumann** [comment]
Hi @kunUCSD sorry for the slow response.

Do you have any content in the *mutationrates_utr.log files in the folder and if yes could you share it?

How did you install slamdunk - via conda or are you using a Docker image?

**Comment by kunUCSD** [comment]
Thanks Tobias,

I re-install conda and slamdunk, and it works now. The previous utr.log is empty. I guess the issue is that the r packages did load well.
Anyway, it works. Thanks.

Best, Kun

Email : kutan@ucsd.edu
________________________________
