### ISSUE TITLE
readCount and tcReadCount

### ISSUE THREAD

**Issue by amitblum** [t-neumann/slamdunk#60]
Hello,
Is the readCount is the number of all reads aligning to the 3’ UTR, including the T>C converted reads or only the non converted reads?

Thanks
Amit

**Comment by t-neumann** [comment]
Total reads so T>C + unconverted reads

**Comment by aksenovavy** [comment]
Hello,

For Differential Expression analysis do you use TcReadCount/ReadCount or ConversionsOnTs/CoverageOnTs as input? What will be the difference in outputs for fold change for these two inputs?
