### ISSUE TITLE
Collapse possible bug in gene length

### ISSUE THREAD

**Issue by KGillinder** [t-neumann/slamdunk#61]
Hi,

It seems that when running alleyoop->collapse the gene length from each record is added together? Is this the intended output?

Other features, for example the rate appears to be averaged.

**Comment by t-neumann** [comment]
Actually all the columns should be summed up, so also the length.

The conversion rate is recalculated based on the new summed counts, probably that's why it appears to be averaged.

**Comment by KGillinder** [comment]
great, thanks for this explanation.
