### ISSUE TITLE
Conversions counts per read

### ISSUE THREAD

**Issue by KGillinder** [t-neumann/slamdunk#63]
It would be great to add another metric for analysis - Counts/conversions per Read. You have calculations based on the position in the read, but not one that investigates the total number observed per read.

**Comment by t-neumann** [comment]
Mhm you can have a proxy for this using `alleyoop dump`:

```
    dump                Print all info available for slamdunk reads
```

But in the end what you need for that would be some read-based output which is a pretty elaborate output and nothing I can envision would be some standard output for downstream analysis.
