### ISSUE TITLE
slamdunk all Unable to locate files

### ISSUE THREAD

**Issue by aparajitadutta** [t-neumann/slamdunk#69]
Where exactly should we keep the fasta, bed and fastq files. I keep getting the following error when running it from py2_env virtual enviromnent:

Traceback (most recent call last):
File "/home/aparajita/py2_env/bin/slamdunk", line 8, in
sys.exit(run())
File "/home/aparajita/py2_env/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 478, in run
runAll(args)
File "/home/aparajita/py2_env/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 233, in runAll
runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
File "/home/aparajita/py2_env/lib/python2.7/site-packages/slamdunk/slamdunk.py", line 148, in runMap
mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
File "/home/aparajita/py2_env/lib/python2.7/site-packages/slamdunk/dunks/mapper.py", line 101, in Map
if(checkStep([inputReference, inputBAM], [replaceExtension(outputSAM, ".bam")], force)):
File "/home/aparajita/py2_env/lib/python2.7/site-packages/slamdunk/utils/misc.py", line 156, in checkStep
raise RuntimeError("One or more input files don't exist!!!!: " + str(inFiles))
RuntimeError: One or more input files don't exist!!!!: ['GRCh38.p10.genome.fa', '1-G7-DMSO-1_S22_L002_R1_001.fastq.gz']

**Comment by t-neumann** [comment]
Can you send the exact slamdunk call?

**Comment by aparajitadutta** [comment]
The slamdunk call is:
slamdunk all -r GRCh38.p10.genome.fa -b utr3.bed -o output/ -5 12 -n 100 -t 10 -m -rl 101 --skip-sam 1-G7-DMSO-1_S22_L002_R1_001.fastq.gz

I have these files in the current directory.

I installed slamdunk in a virtual environment using the command 'pip install slamdunk'

The virtual environment is currently activated when I am executing the slamdunk call.

**Comment by t-neumann** [comment]
Looks like those files do not exist or you don't have access rights to them?

**Comment by t-neumann** [comment]
Also, why don't you install slamdunk directly from bioconda?

conda create --name slamdunk slamdunk

**Comment by aparajitadutta** [comment]
Using the given command: conda create --name slamdunk slamdunk

generates following output:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - slamdunk

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by aparajitadutta** [comment]
Also tried:

 conda create --name myslamdunk -c bioconda slamdunk 

But the output is stuck at:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment:

**Comment by t-neumann** [comment]
I think you need to first set the [correct channel order](https://bioconda.github.io/user/install.html#set-up-channels):

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by aparajitadutta** [comment]
Thank you. The suggestion solved the issue and slamdunk has been installed with the command:

conda create --name myslamdunk -c bioconda slamdunk

However, on activating the conda enviromnent and running the slamdunk call I get the following issue. It seems to be messing up with a previously created virtual environment 'slamdunk_py2env'. This directory is now deleted but it still displays the following error:

(base) aparajita@HP-Z4-G4:~$ conda activate myslamdunk
(myslamdunk) aparajita@HP-Z4-G4:~$ slamdunk all -r GRCh38.p10.genome.fa -b utr3.bed -o output_conda_myslamdunk -5 12 -n 100 -t 10 -m -rl 101 --skip-sam 1-G7-DMSO-1_S22_L002_R1_001.fastq.gz
-bash: /home/aparajita/.local/bin/slamdunk: /home/aparajita/slamdunk_py2env/bin/python: bad interpreter: No such file or directory

**Comment by t-neumann** [comment]
I think your local slamdunk installation is interfering with the conda environment.

Try 
```
export PYTHONNOUSERSITE=1
```
before the slamdunk call.

**Comment by aparajitadutta** [comment]
My heartfelt thanks. 

export PYTHONNOUSERSITE=True 

before activating the conda environment did the trick.
