### ISSUE TITLE
alleyoop utrrates does not estimate read length

### ISSUE THREAD

**Issue by aparajitadutta** [t-neumann/slamdunk#71]
I am not sure whether alleyoop error should be posted here, posting it anyway since it comes with the slamdunk package.

The slamdunk docs says that in the module utrrates, the parameter -l is the Maximum read length in all samples (will be automatically estimated if not set).

However it displays the following error when -l parameter is not provided in the call.

AttributeError: module 'sys' has no attribute 'maxint'

**Comment by t-neumann** [comment]
Hi @aparajitadutta 

yes I am working on a new version that should be released soon during the Corona times where this is fixed. Basically it is an error that came from the recent major transition from py2->py3.

Thanks for pointing it out!
