### ISSUE TITLE
Replace alignment step

### ISSUE THREAD

**Issue by sarahet** [t-neumann/slamdunk#72]
Hi,

I was wondering, if I would like to use another aligner instead of NextGenMap but one that allows for split reads like STAR or Hisat2, would it be possible to apply the other modules on top or would the split reads potentially cause a problem in the count step?
Of course, the BAM file would need to be anyways adjusted in a way that it provides the additional tags that slamdunk expects. But besides this, could there be problems arising from split reads where one half of the read does not contain a conversion while the other does? I would appreciate any comment or further ideas.

Best,
Sara

**Comment by t-neumann** [comment]
hi @sarahet 

as long as the BAM file provides the respective tags, I see no problems arising from split reads.

In fact, we are exploring together with the HISAT2 developers options how to integrate the conversion-aware scoring scheme into HISAT2 and already have a prototype from the HISAT2-end.

Drop me a mail and I can give you further directions.

Cheers,

Tobi

**Comment by sarahet** [comment]
Great, done.
