### ISSUE TITLE
error in alleyoop utrrates

### ISSUE THREAD

**Issue by minaka1484** [t-neumann/slamdunk#76]
Hi Tobias, 

I have a problem when I use alleyoop utrrates. I checked that files are executable, and I reinstall conda and SLAM-DUNK, but it didn't change. I'm a very beginner of bioinformatic analysis, so I might have some mistakes. Could you please have a look at errors and log below, and let me know if you know clues to solve this issue? Your advice is much appreciated.

command:
$ alleyoop utrrates -o alleyoop_all -r Mus_musculus.GRCm38.dna.primary_assembly.fa  -b hgTables.txt  -l 100 
cr59_2/filter/upvl1-1e-cr_ERR2241559_slamdunk_mapped_filtered.bam 
cr60_2/filter/upvl1-1g-cr_ERR2241560_slamdunk_mapped_filtered.bam 
wt49_2/filter/upvl1-1d-wt_ERR2241549_slamdunk_mapped_filtered.bam 
wt50_2/filter/upvl1-1f-wt_ERR2241550_slamdunk_mapped_filtered.bam 
wt51_2/filter/upvl1-1h-wt_ERR2241551_slamdunk_mapped_filtered.bam

log:
Using 100 as maximum read length.
/usr/local/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmpva470i01 -O alleyoop_all/upvl1-1e-cr_ERR2241559_slamdunk_mapped_filtered_mutationrates_utr.pdf
b'During startup - Warning messages:\n'b'1: Setting LC_CTYPE failed, using "C" \n'b'2: Setting LC_COLLATE failed, using "C" \n'b'3: Setting LC_TIME failed, using "C" \n'b'4: Setting LC_MESSAGES failed, using "C" \n'b'5: Setting LC_MONETARY f$

error:
^[[33mWARNING:^[[0m Skipping mount /opt/pkg/singularity/3.5.2/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
Creating output directory: alleyoop_all
Running alleyoop utrrates for 5 files (1 threads)
/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/usr/local/bin/alleyoop", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 495, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 174, in runStatsRatesUTR
    stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
  File "/usr/local/lib/python3.7/site-packages/slamdunk/dunks/stats.py", line 528, in statsComputeOverallRatesPerUTR
    callR(getPlotter("globalRatePlotter") + " -f " + f.name + " -O " + outputPDF, log, dry=printOnly, verbose=verbose)
  File "/usr/local/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 211, in callR
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/usr/local/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmpva470i01 -O alleyoop_all/upvl1-1e-cr_ERR2241559_slamdunk_mapped_filtered_mutationrates_utr.pdf

Thanks,
Minaka

**Comment by t-neumann** [comment]
Hi Minaka,

sorry for the late reply, was on holiday.  I don't see anything apparent off from the first glance - what is the content of this file? `/tmp/tmpva470i01`

And this I guess is a regular bed file?  `hgTables.txt`

**Comment by minaka1484** [comment]
Hi Tobias,

Thank you very much for your replying. 

I searched for /tmp/tmpva470i01, but there is no file named tmpva470i01. hgTables.txt is like this.
chr1	134199222	134201713	ENSMUST00000169927.1_utr3_0_0_chr1_134199223_r	0	-

I was checking output files in the count folder, and I noticed that numbers in my tsv files are all 0 or -1 after 7th row like this.
Chromosome	Start	End	Name	Length	Strand	ConversionRate	ReadsCPM	Tcontent	CoverageOnTs	ConversionsOnTs	ReadCount	TcReadCount	multimapCount	ConversionRateLower	ConversionRateUpper
chr1	134199222	134201713	ENSMUST00000169927.1_utr3_0_0_chr1_134199223_r	2491	-	0	0	0	0	0	0	0	0	-1.0	-1.0

I used slamdunk count individually as well.
$slamdunk count -o count_test -s ../snp -r ../../Mus_musculus.GRCm38.dna.primary_assembly.fa -b ../../hgTables.txt ../filter/upvl1-1e-cr_ERR2241559_slamdunk_mapped_filtered.bam
And I got an error message like following.
Creating output directory: count_test
Running slamDunk tcount for 1 files (1 threads)
Traceback (most recent call last):
  File "/usr/local/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 474, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory) for tid in range(0, len(args.bam)))
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 189, in runCount
    maxLength = estimateMaxReadLength(bam)
  File "/usr/local/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 95, in estimateMaxReadLength
    minLength = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'

Does this have anything to do with utrrate error? Or do you think this is different issue? Thank you very much for your support.

Thanks,
Minaka

**Comment by t-neumann** [comment]
Hi,

it looks like you are running and older version of slamdunk. What does `slamdunk --version` give you?

**Comment by minaka1484** [comment]
Hi Tobias,

Thank you so much for your replying. I used a server and my computer, and got messages above. You are right. The version of slamdunk for the server was 0.4.1 and for my computer was 0.4.3. Is this the reason why I was getting the error messages? I was using the server because my computer has difficulty for mapping. But now I’m processing same data with my computer and try to see what will happen with 0.4.3. Thank you very much for your kind support. 

Thanks,
Minaka

**Comment by t-neumann** [comment]
Ok keep me posted

**Comment by jmbillingsley** [comment]
Greetings! I might have a related problem here. alleyoop utrrates fails when plotting the pdf.  My command for a single filtered bam file is

**Comment by jmbillingsley** [comment]
alleyoop utrrates -o /home/jmb17/SlamdunkTest/plots -r /n/shared_db/bcbio/biodata/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.fa -t 1 -b /home/jmb17/SlamdunkTest/BEDforSlamdunkv1.bed -l 100 /home/jmb17/SlamdunkTest/output/filter/ctrl_pi-transcriptome_slamdunk_mapped_filtered.bam

**Comment by jmbillingsley** [comment]
and the error in the filtered_mutationrates_utr.log  file is b'Error: package or namespace load failed for \xe2\x80\x98ggplot2\xe2\x80\x99:\n'b' package \xe2\x80\x98ggplot2\xe2\x80\x99 was installed before R 4.0.0: please re-install it\n'b(((sl((     

Many thanks!   James

**Comment by t-neumann** [comment]
@jmbillingsley Are you running it out of a container or conda environment?

**Comment by jmbillingsley** [comment]
conda environment

**Comment by jmbillingsley** [comment]
on a high performance cluster

**Comment by jmbillingsley** [comment]
Yes of course, thanks so much for the offer.  I’ll try to upload to dropbox, and send you a link. stand by.






On Jun 25, 2020, at 5:03 AM, Tobias Neumann <notifications@github.com<mailto:notifications@github.com>> wrote:



Is there a chance you supply me with your fasta, bed and bam file, so I can try this on my end?

**Comment by jmbillingsley** [comment]
https://www.dropbox.com/sh/r9aqbvafojf7ff0/AADa38T9_zpa1Rkjg-t0LMKoa?dl=0

**Comment by jmbillingsley** [comment]
Greetings. It appears that my issues appear to be more upstream than I’d initially thought.

I examined the mapped_filtered_tcount.tsv files and all the output are 0, so the slamdunk all analysis is failing.

I ran this on a sorted bam file generated from paired fastq files in our standard RNA-Seq pipeline.

I’ve included the sorted bam file and the tsv output in that dropbox directory.

I’m of course happy to provide log file output if you’d like.

Thanks!










On Jun 25, 2020, at 3:58 PM, Billingsley, James Michael <jbillingsley@hsph.harvard.edu<mailto:jbillingsley@hsph.harvard.edu>> wrote:

https://www.dropbox.com/sh/r9aqbvafojf7ff0/AADa38T9_zpa1Rkjg-t0LMKoa?dl=0

**Comment by t-neumann** [comment]
Hi James,

sorry for taking forever to get back to you, was in the middle of 2 concurrent paper submissions.

So I checked your files and I know what is going on:

Slamdunk utilized custom bam tags (MP:Z and RA:Z) for rapid mismatch extraction which we get directly from the aligner (NextGenMap and also the upcoming HISAT2-TLA). Furthermore, from what I can see you aligned against the transcripts instead of the genome, that could cause additional problems depending on how you handle multimappers. Because you will run into multimappers for transcript variants.
