### ISSUE TITLE
Is slamdunk suitable for single cell SLAM-seq analysis

### ISSUE THREAD

**Issue by pigraul** [t-neumann/slamdunk#77]
Hi Tobias,

Is slamdunk suitable for single cell SLAM-seq analysis ?

Thank you

**Comment by t-neumann** [comment]
Hi @pigraul 

also sorry for the late reply, I was on holiday.

So in principal, slamdunk should also be able to map single-cell SLAM-seq reads, but it does not provide any demultiplexing option, so you would need to separate the read sets into your bins on your own before mapping them.
