### ISSUE TITLE
Pathing issues

### ISSUE THREAD

**Issue by Furciferi** [t-neumann/slamdunk#84]
Im installing this on a HPC for a user.

Not sure why but when installing from bioconda theres annoying pathing issues with using the import statements with the package referenced

eg running slamdunk -h from shell gives no module named dunks.

Suggest using explicit imports or some other workaround
from .dunks import tcounter
instead of
from slamdunk.dunks import tcounter

**Comment by t-neumann** [comment]
How did you install slamdunk exactly?

**Comment by Furciferi** [comment]
Ah yes sorry.

conda create --name slamd -c bioconda slamdunk

The package doesnt allow import to be loaded from the slamdunk.py

from slamdunk.slamdunk import run

Breaks - but

from slamdunk.dunks import tcounter works completely fine.

I changed the three
from slamdunk.XXXXX import <>
in the  allyoop, slamdunk and splash files to use .dunk , .utils etc and it loads fine

**Comment by t-neumann** [comment]
Hm that is weird - can you please try the following?

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge

conda create --name slamd slamdunk
```

**Comment by Furciferi** [comment]
So that fixed it...

How strange...

**Comment by Furciferi** [comment]
Cheers
