### ISSUE TITLE
[E::idx_find_and_load] errors

### ISSUE THREAD

**Issue by shokohirosue** [t-neumann/slamdunk#85]
Hi, thank you for developing and maintaining a great package.

This may not be directly relevant to slamdunk itself, but when I run `slamdunk all` I get 

[E::idx_find_and_load] Could not retrieve index file for '/output/directory/map/sample1_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for '/output/directory/filter/sample1_slamdunk_mapped_filtered.bam'...etc.

There is no index file associated with '/output/directory/map/sample1_slamdunk_mapped.bam', but there are '/output/directory/filter/sample1_slamdunk_mapped_filtered.bam.bai' Despite all these error messages, I get the final count result.

Do you have any ideas why I am failing to make index files? And do you think these errors affect the count output?

Thank you very much for your help.

**Comment by t-neumann** [comment]
Hi Shoko,

so not having a index file for the mapped bam files is ok (they are not coordinate sorted anyways), the one for the filtered bam file is weird. What was the command that your ran? And how did you install slamdunk?

Did you check if in the count files you actually also have read counts? Or is it all zero?

Cheers

**Comment by shokohirosue** [comment]
Hi Tobi,

Thank you so much for the prompt reply!

- I see '.bam.bai' files in filter folder as I described previously.

- The command I ran looks like this:

`slamdunk all -r $genome -b $utr3 -o '/output/directory' -5 12 -n 100 -t 12 -m -rl 100 /input/directory/*`

- And I installed slamdunk using conda.

- The top lines of one of the output tsv files look like this:

Chromosome      Start   End     Name    Length  Strand  ConversionRate  ReadsCPM        Tcontent        CoverageOnTs    ConversionsOnTs ReadCount       TcReadCount     mult
imapCount   ConversionRateLower     ConversionRateUpper
chr22   29442122        29442455        5988    333     +       0       0       112     0       0       0       0       0       -1.0    -1.0
chr19   13961529        13962694        5989    1165    -       0.0     10.577765414710909      242     2833    0       242     0       0       -1.0    -1.0
chr12   109448654       109451813       83892   3159    -       0.0005251181515841065   43.18525714766272       921     11426   6       988     6       22      -1.0    -1.0
chr12   109456117       109456313       83892   196     -       0.0     0.04370977444095417     57      11      0       1       0       0       -1.0    -1.0
chr12   109457629       109457682       83892   53      -       0       0       10      0       0       0       0       0       -1.0    -1.0
chr12   109457991       109458078       83892   87      -       0       0       20      0       0       0       0       0       -1.0    -1.0


Thank you for your help!

**Comment by t-neumann** [comment]
Ok so it indeed also counts some reads - maybe then you can ignore it.

Last check, this file from the warning message, does it exist?
```
/output/directory/filter/sample1_slamdunk_mapped_filtered.bam.bai
```

**Comment by shokohirosue** [comment]
yes they do exist (even though the error messages seem to complain there don't).

**Comment by t-neumann** [comment]
Ok then leave this open for now, but looks like it works. I would have only been worried if zero reads were retreived since than clearly the index file would not have been read properly.

**Comment by shokohirosue** [comment]
Ok! That's reassuring, thank you for your help! Plz keep me updated :)

**Comment by leoTiez** [comment]
I had the same issue whilst changing the framework a bit to fit our needs. My current understanding is that this error is raised by the `pyslam` library (I assume that it's this line https://github.com/pysam-developers/pysam/blob/b09ddca07b10bdd5d25be519e26a8d947435f83d/htslib/hts.c#L3959). Apparently, the first warning is thrown because during the `filter` process `pyslam` can't open the bam index file in the map folder. Indeed, there's none created during `map`. It should do the trick when you change the

**Comment by t-neumann** [comment]
Hi,

you should not sort the map.bam output file if you plan to recover multimappers. Those are output in successive chunks and if you sort them, these chunks will be dissolved and the filter algorihm does not work properly anymore.

**Comment by leoTiez** [comment]
OK cool, good comment! I didn't know that. I assume then that the `idx_find_and_load` error can be indeed ignored or silenced as the bai files from the mapper wouldn't be used anyways in the downstream analysis.
