### ISSUE TITLE
3'UTR bed file

### ISSUE THREAD

**Issue by peneder** [t-neumann/slamdunk#87]
Dear Tobias,

cool tool! I am currently trying to re-create some of your analysis for our own paper, and came across the following section ([in the supplement of the Muhar et al paper](https://science.sciencemag.org/content/sci/suppl/2018/04/04/science.aao2793.DC1/aao2793-Muhar-SM.pdf))
_"Gene  and  3'  UTR  annotations  were  obtained  from  the  UCSC  table  browser (https://genome.ucsc.edu/cgi-bin/hgTables,  June  2016).  3’  UTR  annotations  were assigned  to  Entrez  GeneIDs  and  collapsed  on  a  per-gene  basis  using  bedtools’ merge command  (38).    For  genes  lacking  an  annotated  3'  UTR,  Ensembl  v84  3'  UTRs  were added  if  available,  resulting  in  a  total  of  58136  annotated  3'  UTR  intervals  for  25420 genes."_

Would it be possible that you provide the resulting .bed file (for hg38) as a reference here on the github repo? It would be useful for me (and probably some other people as well).

Thanks,
Peter

**Comment by t-neumann** [comment]
Hi Peter,

it's actually supplied on GEO:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE100708

Check the Supplementary files on the bottom.

Cheers

**Comment by peneder** [comment]
Awesome, thanks a lot!
