### ISSUE TITLE
slamDunk for totalRNA kit

### ISSUE THREAD

**Issue by kopardev** [t-neumann/slamdunk#89]
Can SlumDunk be used to analyze 4SU labeled mRNA which has been sequenced with totalRNA kit? If yes, what are your recommendations for the same? Thanks.

**Comment by t-neumann** [comment]
Hi @kopardev ,

I replied to your email - currently you kind of have to hack Slamdunk to align to transcript fasta files and use the transcript lengths as bed entires (disable multimapper filtering) to get a crude analysis, but we are working on a proper solution which I also forwarded you the contact.

Cheers

**Comment by kopardev** [comment]
Thanks, Tobias. I appreciate your suggestions.
