### ISSUE TITLE
3' UTR file generation

### ISSUE THREAD

**Issue by zsun89** [t-neumann/slamdunk#90]
Hi slamdunk developers,

I'm new to SLAMseq seq analysis and was wondering how should I generate a proper 3'UTR file for the analysis. I tried with the UCSC table browser (mm10) to download 3'UTR annotation file as suggested by Matsushima et al. Nature Protocol 2019 (steps 44-49). However, I noticed there are entries that have exactly the same start and end position (see bellow **bold**), which I assume are 3'UTRs originated from transcripts with different start position and same end (3') position. Would these 'duplicate' entries be a problem for the slamdunk pipeline?
Additionally, the name field (column 4) of these BED files are not ideal for alleyoop collapse since 3'UTR entries from the same gene do not share the same name, but have distinct transcript names (see below _italic_). Therefore, I cannot generate a collapsed tcount file for gene level differential expression analysis.

chr1	134199222	134201713	ENSMUST00000169927.1_utr3_0_0_chr1_134199223_r	0	-
_chr1	134202064	134202950	ENSMUST00000169927.1_utr3_1_0_chr1_134202065_r	0	-
chr1	134199224	134202950	ENSMUST00000086465.5_utr3_0_0_chr1_134199225_r	0	-
chr1	134201348	134202950	ENSMUST00000038191.7_utr3_0_0_chr1_134201349_r	0	-_
**chr1	8361474	8363474	ENSMUST00000132064.7_utr3_0_0_chr1_8361475_r	0	-
chr1	8361474	8363474	ENSMUST00000191683.5_utr3_0_0_chr1_8361475_r	0	-
chr1	8361474	8363474	ENSMUST00000140295.7_utr3_0_0_chr1_8361475_r	0	-**
chr1	25067475	25068167	ENSMUST00000126626.7_utr3_0_0_chr1_25067476_r	0	-
chr1	25067549	25068167	ENSMUST00000135518.7_utr3_0_0_chr1_25067550_r	0	-
chr1	25067549	25068167	ENSMUST00000151309.7_utr3_0_0_chr1_25067550_r	0	- 

Thanks,
Zhen

**Comment by zsun89** [comment]
I tried and solved these issues by assigning transcripts to genes and replaced extracted transcript ID with gene ID. Then I merged overlapping 3'UTRs and generated a collapsed 3'UTR BED file.

**Comment by zsun89** [comment]
I found an issue when revisiting the analysis: generating collapsed UTR files (merge overlapping UTRs) sometimes results in UTRs of different genes being merged together. For example, microRNA genes that falls within the UTR of a protein coding gene. Do we have to use a collapsed UTR file during the mapping step? Would using a non-collapsed UTR file cause problems in multimapper reconciliation due to the existence of overlapping features?

**Comment by t-neumann** [comment]
Hi @zsun89 sorry for the late reply. Usually if such UTRs overlap, they do it on different strands and since QuantSeq is a stranded assay, you are still able to differentiate signal in overlapping windows.

If you have the counting windows on the same strand and overlapping, there is not much you can do - you will get ambiguous information for that gene unless on or the other gene is not expressed.
