### ISSUE TITLE
Alleyoop dedup

### ISSUE THREAD

**Issue by snaqvi1990** [t-neumann/slamdunk#93]
Hello,

This is more of a methodological question about the alleyoop pipeline. We noticed that there is a dedup command - is it recommended to run this prior to running slamdunk count? We could not find any reference to deduplication in the published papers that use SLAM-dunk. I know that generally deduplication is not performed with RNA-seq libraries unless UMIs are present, but I am curious if there are specific reasons to do it for SLAM-seq/Quant-seq libraries.

Thanks,
Sahin

**Comment by t-neumann** [comment]
Hi Sahin,

no we actually also have not explored more in that regard. So for now I do not recommend to run the dedup command before counting.

Best,

Tobi
