### ISSUE TITLE
default 12bp trimming from 5' end

### ISSUE THREAD

**Issue by snaqvi1990** [t-neumann/slamdunk#94]
Hello,

Another unrelated question - slamdunk by default seems to trim 12bp from the 5' end of the read - what is the purpose of this step? Is it related to read quality, or something more specific to SLAMseq analyses?

Thanks,
Sahin

**Comment by t-neumann** [comment]
Hi Sahin,

this is more a Quantseq specific setting where the kit manufacturer recommends to trim the first 12bp from the 5' end.

Best,

Tobi

**Comment by snaqvi1990** [comment]
Hi Tobi,

Thanks for the response. If the trimming is done, should the -l parameter in slamdunk count then be adjusted to accounted for this (i.e. if sequenced read length is 150, -l should be 138)?

Thanks,
Sahin

**Comment by t-neumann** [comment]
Hi Sahin,

no that's fine - leave it at the untrimmed read length.

Best,

Tobi
