### ISSUE TITLE
Output .bam of T-C containing reads?

### ISSUE THREAD

**Issue by snaqvi1990** [t-neumann/slamdunk#95]
Hello,

I was wondering if there was a way to separate T-C from non-T-C containing reads using slamdunk? I know that count does this internally and then outputs a .bedgraph file, but I would like to get the actual .bams corresponding to TC and non-TC (or total) reads.

Thanks,
Sahin

**Comment by t-neumann** [comment]
You can do that with `alleyoop read-separator` - should be quite self-explanatory.
